/* ==========================================================================
   BRAND-CONFIG.JS — Clearpath

   >>> THIS IS THE ONLY FILE YOU NEED TO EDIT. <<<

   Everything below drives the whole site: brand name, colours, products,
   prices, testimonials, FAQs, and the Shopify redirect links.

   TO GO LIVE, YOU MUST:
     1. Replace every checkoutUrl with the real Shopify product URL.
     2. Replace every [[PLACEHOLDER: ...]] string.
     3. Replace the images in images/ and images/products/ with real photos.
     4. Add real tracking IDs below and set tracking.enabled to true.
     5. Remove the noindex tag from every .html file (search for "noindex").

   Find every remaining placeholder at once:
     grep -rn "PLACEHOLDER" .           (Mac/Linux)
     findstr /s /n "PLACEHOLDER" *.*    (Windows)
   ========================================================================== */

var BRAND = {
  name: "Clearpath",
  tagline: "For the hours that decide the rest of your day.",
  announcement: "Free discreet shipping over $50",
  logo: 'images/logo.svg',

  /* ---- Colours. theme-init.js applies these before first paint. -------- */
  colors: {
  "background": "#ffffff",
  "surface": "#f4f6fb",
  "soft": "#eef0f8",
  "text": "#1b2333",
  "heading": "#141a28",
  "muted": "#5d6782",
  "border": "#dfe3ef",
  "borderStrong": "#c3cade",
  "accent": "#4a5aa0",
  "accentHover": "#3a477f",
  "accentTint": "#e8ebf7",
  "onAccent": "#ffffff",
  "footerBg": "#141a28",
  "footerText": "#c5cbdd",
  "star": "#d9a02e"
},

  style: {
  "radius": "16px",
  "radiusLarge": "20px",
  "buttonRadius": "999px",
  "cardStyle": "elevated",
  "logoWidth": "146px"
},

  currency: {
  "symbol": "$",
  "code": "USD",
  "decimals": 2
},

  /* Every category has its own page. Generated by _tools/generate.js. */
  categoryPages: {
  "Evening": "evening.html",
  "Rituals": "rituals.html",
  "Bundles": "bundles.html"
},
  categoryIndex: {
  "Evening": 1,
  "Rituals": 2,
  "Bundles": 3
},
  categoryIcons: {},

  contact: {
    email: "support@clearpath-placeholder.com",
    phone: "+1 (555) 010-7734",
    hours: "Mon–Fri, 9am–8pm ET",
    address: "[[PLACEHOLDER: registered business address]]",
    legalEntity: "Clearpath Wellbeing Ltd"
  },

  /* ---- Footer health disclaimer. Ad reviewers read this. --------------- */
  disclaimer: "[[PLACEHOLDER: health disclaimer]] The content on this site is for general information only and is not medical advice. Always speak to a qualified healthcare professional before starting, stopping or changing anything related to your health. Products are not intended to diagnose, treat, cure or prevent any disease.",

  copy: {
    buyCta: 'Buy now'
  },

  /* ---- Ad pixels. Nothing loads or fires until enabled is true. -------- */
  tracking: {
    enabled: false,
    ga4MeasurementId: '',            // 'G-XXXXXXXXXX'
    googleAdsConversionId: '',       // 'AW-XXXXXXXXX'
    googleAdsConversionLabel: '',    // the label from the conversion action
    metaPixelId: ''                  // numeric ID only
  },

  seo: {
    /* Leave false until a real review app supplies ratings. Invented ratings
       in structured data get Merchant Center accounts suspended. */
    emitAggregateRating: false
  },

  heroProof: [
  "Licensed providers",
  "Plain packaging",
  "Cancel anytime"
],
  marquee: [
  "Free shipping over $50",
  "Plain, unbranded packaging",
  "30-day returns",
  "Cancel anytime",
  "Support replies in 24h",
  "Full ingredient lists"
],
  goals: [],
  heroProducts: [],
  newArrivals: [],
  qualityPicks: [],
  spotlightSlug: "",
  promo: {
  "tag": "Limited offer",
  "heading": "[[PLACEHOLDER]] 15% off your first order",
  "text": "[[PLACEHOLDER]] Applies to everything in the range. One use per customer.",
  "code": "WELCOME15",
  "cta": "Shop the offer"
},
  valueProps: [
  {
    "icon": "clock",
    "text": "Built for evenings"
  },
  {
    "icon": "box",
    "text": "Discreet packaging"
  },
  {
    "icon": "truck",
    "text": "Free shipping over $50"
  },
  {
    "icon": "chat",
    "text": "Support in 24h"
  }
],
  howItWorks: [
  {
    "title": "Answer a few questions",
    "text": "[[PLACEHOLDER]] A short set of questions about your evenings and what you have already tried."
  },
  {
    "title": "Get a recommendation",
    "text": "[[PLACEHOLDER]] We suggest a starting point, and tell you if we think you should speak to a professional first."
  },
  {
    "title": "Delivered to your door",
    "text": "[[PLACEHOLDER]] Plain outer packaging, on a schedule you can change at any time."
  }
],
  trustBadges: [
  {
    "icon": "stethoscope",
    "title": "Licensed providers",
    "text": "[[PLACEHOLDER: substantiate before launch]]"
  },
  {
    "icon": "lock",
    "title": "Secure checkout",
    "text": "Payments handled by an encrypted provider."
  },
  {
    "icon": "box",
    "title": "Discreet packaging",
    "text": "Plain outer packaging, no branding outside."
  },
  {
    "icon": "refresh",
    "title": "Money-back guarantee",
    "text": "[[PLACEHOLDER: confirm real terms]]"
  }
],
  productReassurance: [
  {
    "icon": "truck",
    "text": "Free shipping on orders over $50"
  },
  {
    "icon": "box",
    "text": "Plain, unbranded outer packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day return window on unopened items"
  },
  {
    "icon": "lock",
    "text": "Secure checkout"
  }
],
  values: [
  {
    "icon": "shield",
    "title": "Transparent by default",
    "text": "[[PLACEHOLDER]] Full ingredient lists and honest labelling on everything we sell."
  },
  {
    "icon": "stethoscope",
    "title": "Guided by professionals",
    "text": "[[PLACEHOLDER]] Our range is reviewed by qualified practitioners."
  },
  {
    "icon": "leaf",
    "title": "Thoughtfully sourced",
    "text": "[[PLACEHOLDER]] We work with suppliers who meet our quality standards."
  },
  {
    "icon": "chat",
    "title": "Support that answers",
    "text": "[[PLACEHOLDER]] Real people, replying within one business day."
  }
],
  stats: [
  {
    "value": "10k+",
    "label": "[[PLACEHOLDER]] orders delivered"
  },
  {
    "value": "4.8",
    "label": "[[PLACEHOLDER]] average rating"
  },
  {
    "value": "24h",
    "label": "[[PLACEHOLDER]] support response"
  },
  {
    "value": "30d",
    "label": "[[PLACEHOLDER]] returns window"
  }
],
  aboutPoints: [
  "[[PLACEHOLDER]] Every product reviewed before it joins the range",
  "[[PLACEHOLDER]] Clear ingredient lists, no proprietary blends",
  "[[PLACEHOLDER]] Plain packaging on every order",
  "[[PLACEHOLDER]] Cancel or change a subscription at any time"
]
};

/* ==========================================================================
   PRODUCTS
   checkoutUrl is the ONE integration point with your real Shopify store.
   Replace each one with the real product URL, e.g.
     'https://yourstore.com/products/daily-foundation'
   Buttons navigate there in the same tab after firing a tracking event.
   ========================================================================== */

var PRODUCTS = [
  {
    "slug": "night-capsules",
    "name": "Night Capsules",
    "sku": "CLEARPATH-NIGHTCAPSULE",
    "category": "Evening",
    "shortBenefit": "A once-nightly capsule for the end of your routine.",
    "description": "[[PLACEHOLDER]] A once-nightly capsule for the end of your routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Night Capsules from Clearpath. A once-nightly capsule for the end of your routine.",
    "price": 38,
    "compareAt": 46,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 742,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "One capsule at night",
      "30-day supply",
      "Clear ingredient list"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take before bed as directed on the label. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/night-capsules.svg",
    "gallery": [
      "images/products/night-capsules.svg",
      "images/products/_angle-evening-2.svg",
      "images/products/_angle-evening-3.svg",
      "images/products/_angle-evening-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Night Capsules]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/night-capsules"
  },
  {
    "slug": "calm-drops",
    "name": "Calm Drops",
    "sku": "CLEARPATH-CALMDROPS",
    "category": "Evening",
    "shortBenefit": "A liquid option for people who dislike capsules.",
    "description": "[[PLACEHOLDER]] A liquid option for people who dislike capsules. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Calm Drops from Clearpath. A liquid option for people who dislike capsules.",
    "price": 42,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.6,
    "reviewCount": 511,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Measured dropper",
      "Unflavoured",
      "30ml bottle"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Use the dropper as directed on the label in the evening.",
    "image": "images/products/calm-drops.svg",
    "gallery": [
      "images/products/calm-drops.svg",
      "images/products/_angle-evening-2.svg",
      "images/products/_angle-evening-3.svg",
      "images/products/_angle-evening-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Calm Drops]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/calm-drops"
  },
  {
    "slug": "wind-down-tea",
    "name": "Wind Down Tea",
    "sku": "CLEARPATH-WINDDOWNTEA",
    "category": "Rituals",
    "shortBenefit": "A caffeine-free evening ritual.",
    "description": "[[PLACEHOLDER]] A caffeine-free evening ritual. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Wind Down Tea from Clearpath. A caffeine-free evening ritual.",
    "price": 22,
    "compareAt": 28,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 894,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "30 bags per tin",
      "Caffeine-free",
      "Loose-leaf option available"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Steep as directed on the tin, ideally an hour before bed.",
    "image": "images/products/wind-down-tea.svg",
    "gallery": [
      "images/products/wind-down-tea.svg",
      "images/products/_angle-rituals-2.svg",
      "images/products/_angle-rituals-3.svg",
      "images/products/_angle-rituals-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Wind Down Tea]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/wind-down-tea"
  },
  {
    "slug": "magnesium-night",
    "name": "Magnesium Night",
    "sku": "CLEARPATH-MAGNESIUMNIG",
    "category": "Evening",
    "shortBenefit": "A simple, single-ingredient evening option.",
    "description": "[[PLACEHOLDER]] A simple, single-ingredient evening option. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Magnesium Night from Clearpath. A simple, single-ingredient evening option.",
    "price": 30,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 623,
    "badge": "New",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "One ingredient, clearly stated",
      "60 capsules",
      "Third-party tested"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take in the evening as directed on the label.",
    "image": "images/products/magnesium-night.svg",
    "gallery": [
      "images/products/magnesium-night.svg",
      "images/products/_angle-evening-2.svg",
      "images/products/_angle-evening-3.svg",
      "images/products/_angle-evening-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Magnesium Night]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/magnesium-night"
  },
  {
    "slug": "silk-sleep-mask",
    "name": "Silk Sleep Mask",
    "sku": "CLEARPATH-SILKSLEEPMAS",
    "category": "Rituals",
    "shortBenefit": "A physical part of the routine, not a supplement.",
    "description": "[[PLACEHOLDER]] A physical part of the routine, not a supplement. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask from Clearpath. A physical part of the routine, not a supplement.",
    "price": 34,
    "compareAt": 42,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 288,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Adjustable strap",
      "Machine washable bag included",
      "Blocks light fully"
    ],
    "ingredients": [
      "[[PLACEHOLDER: material composition]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Wear as part of your evening routine. Hand wash as directed on the care label.",
    "image": "images/products/silk-sleep-mask.svg",
    "gallery": [
      "images/products/silk-sleep-mask.svg",
      "images/products/_angle-rituals-2.svg",
      "images/products/_angle-rituals-3.svg",
      "images/products/_angle-rituals-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-sleep-mask"
  },
  {
    "slug": "evening-ritual-set",
    "name": "Evening Ritual Set",
    "sku": "CLEARPATH-EVENINGRITUA",
    "category": "Bundles",
    "shortBenefit": "Capsules, tea and a sleep mask together.",
    "description": "[[PLACEHOLDER]] Capsules, tea and a sleep mask together. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Evening Ritual Set from Clearpath. Capsules, tea and a sleep mask together.",
    "price": 84,
    "compareAt": 108,
    "priceNote": "one-off purchase",
    "rating": 4.8,
    "reviewCount": 164,
    "badge": "Save 22%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Covers the whole evening routine",
      "Arrives in one box",
      "Cheaper than buying separately"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the directions on each item in the set.",
    "image": "images/products/evening-ritual-set.svg",
    "gallery": [
      "images/products/evening-ritual-set.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Evening Ritual Set]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/evening-ritual-set"
  }
];

/* ========================================================================== */

var TESTIMONIALS = [
  {
    "name": "Adam F.",
    "role": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] The whole thing is calm — the site, the packaging, the emails. It suits what they sell.",
    "avatar": "images/avatars/avatar-1.svg"
  },
  {
    "name": "Maya H.",
    "role": "[[PLACEHOLDER]] Verified customer",
    "rating": 4,
    "quote": "[[PLACEHOLDER]] Straightforward to order and easy to pause. Support replied the next morning.",
    "avatar": "images/avatars/avatar-2.svg"
  },
  {
    "name": "Ben C.",
    "role": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] Appreciated that they told me to check with my GP rather than just taking the order.",
    "avatar": "images/avatars/avatar-3.svg"
  }
];

/* Shown above the reviews. Replace with real aggregate numbers, or delete the
   block from index.html — invented ratings must not reach structured data. */
var REVIEWS_SUMMARY = {
  "rating": 4.8,
  "count": "[[PLACEHOLDER: review count]]"
};

var FAQS = [
  {
    "q": "How do I place an order?",
    "a": "[[PLACEHOLDER]] Choose the product you want and select Buy now. You will be taken to our secure store to complete checkout."
  },
  {
    "q": "How long does delivery take?",
    "a": "[[PLACEHOLDER: confirm real timings]] Orders are usually prepared for dispatch within a couple of business days. Delivery estimates are shown at checkout."
  },
  {
    "q": "Is the packaging discreet?",
    "a": "[[PLACEHOLDER]] Yes. Orders arrive in plain outer packaging with no product branding on the outside."
  },
  {
    "q": "Can I return something?",
    "a": "[[PLACEHOLDER: confirm real policy]] Unopened items can be returned within the window shown at checkout. Some health and personal care items cannot be returned once opened."
  },
  {
    "q": "Do you offer a subscription?",
    "a": "[[PLACEHOLDER]] Where a repeat option is available it is shown on the product page at checkout, and you can change or cancel it at any time."
  },
  {
    "q": "Should I speak to a healthcare professional first?",
    "a": "[[PLACEHOLDER]] If you are pregnant or breastfeeding, take prescription medicine, or have an existing medical condition, speak to a qualified healthcare professional before starting anything new. See our medical disclaimer."
  },
  {
    "q": "How do I contact support?",
    "a": "[[PLACEHOLDER]] Use the contact form, or email us directly. We aim to reply within one business day."
  },
  {
    "q": "Where do you ship?",
    "a": "[[PLACEHOLDER: list real destinations]] Shipping destinations and rates are shown at checkout."
  }
];
