/* ==========================================================================
   BRAND-CONFIG.JS — Vitality Rx

   >>> THIS IS THE ONLY FILE YOU NEED TO EDIT. <<<

   Everything below drives the whole site: brand name, colours, products,
   prices, testimonials, FAQs, and the Shopify redirect links.

   TO GO LIVE, YOU MUST:
     1. Replace every checkoutUrl with the real Shopify product URL.
     2. Replace every [[PLACEHOLDER: ...]] string.
     3. Replace the images in images/ and images/products/ with real photos.
     4. Add real tracking IDs below and set tracking.enabled to true.
     5. Remove the noindex tag from every .html file (search for "noindex").

   Find every remaining placeholder at once:
     grep -rn "PLACEHOLDER" .           (Mac/Linux)
     findstr /s /n "PLACEHOLDER" *.*    (Windows)
   ========================================================================== */

var BRAND = {
  name: "Vitality Rx",
  tagline: "Everyday support for men who want to stay ahead of it.",
  announcement: "Free discreet shipping on orders over $50",
  logo: 'images/logo.svg',

  /* ---- Colours. theme-init.js applies these before first paint. -------- */
  colors: {
  "background": "#ffffff",
  "surface": "#f4f7f7",
  "soft": "#eef4f3",
  "text": "#0f2d3d",
  "heading": "#0b2331",
  "muted": "#5a7280",
  "border": "#dde7e8",
  "borderStrong": "#c3d3d5",
  "accent": "#0e7c66",
  "accentHover": "#0a5f4e",
  "accentTint": "#e2f1ed",
  "onAccent": "#ffffff",
  "footerBg": "#0b2331",
  "footerText": "#c2d4d9",
  "star": "#e0a12c"
},

  style: {
  "radius": "14px",
  "radiusLarge": "18px",
  "buttonRadius": "999px",
  "cardStyle": "bordered",
  "logoWidth": "150px"
},

  currency: {
  "symbol": "$",
  "code": "USD",
  "decimals": 2
},

  /* Every category has its own page. Generated by _tools/generate.js. */
  categoryPages: {
  "Daily essentials": "daily-essentials.html",
  "Sleep & recovery": "sleep-recovery.html",
  "Hair & skin": "hair-skin.html",
  "Bundles": "bundles.html"
},
  categoryIndex: {
  "Daily essentials": 1,
  "Sleep & recovery": 2,
  "Hair & skin": 3,
  "Bundles": 4
},
  categoryIcons: {},

  contact: {
    email: "support@vitality-rx-placeholder.com",
    phone: "+1 (555) 010-4477",
    hours: "Mon–Fri, 9am–6pm ET",
    address: "[[PLACEHOLDER: registered business address]]",
    legalEntity: "Vitality Rx Ltd"
  },

  /* ---- Footer health disclaimer. Ad reviewers read this. --------------- */
  disclaimer: "[[PLACEHOLDER: health disclaimer]] The content on this site is for general information only and is not medical advice. Always speak to a qualified healthcare professional before starting, stopping or changing anything related to your health. Products are not intended to diagnose, treat, cure or prevent any disease.",

  copy: {
    buyCta: 'Buy now'
  },

  /* ---- Ad pixels. Nothing loads or fires until enabled is true. -------- */
  tracking: {
    enabled: false,
    ga4MeasurementId: '',            // 'G-XXXXXXXXXX'
    googleAdsConversionId: '',       // 'AW-XXXXXXXXX'
    googleAdsConversionLabel: '',    // the label from the conversion action
    metaPixelId: ''                  // numeric ID only
  },

  seo: {
    /* Leave false until a real review app supplies ratings. Invented ratings
       in structured data get Merchant Center accounts suspended. */
    emitAggregateRating: false
  },

  heroProof: [
  "Licensed providers",
  "Discreet packaging",
  "Cancel anytime"
],
  marquee: [
  "Free shipping over $50",
  "Plain, unbranded packaging",
  "30-day returns",
  "Cancel anytime",
  "Support replies in 24h",
  "Full ingredient lists"
],
  bento: [
  {
    "icon": "shield",
    "title": "Nothing hidden",
    "text": "[[PLACEHOLDER]] Every quantity printed on the label. No proprietary blends.",
    "wide": true
  },
  {
    "stat": "30",
    "title": "Day returns",
    "text": "[[PLACEHOLDER]] On unopened items.",
    "accent": true
  },
  {
    "icon": "box",
    "title": "Plain packaging",
    "text": "[[PLACEHOLDER]] No branding on the outside of any parcel."
  },
  {
    "icon": "chat",
    "title": "Real support",
    "text": "[[PLACEHOLDER]] A person replies within one business day."
  },
  {
    "icon": "refresh",
    "title": "Change anytime",
    "text": "[[PLACEHOLDER]] Pause, skip or cancel yourself."
  }
],
  compareOther: "Typical pharmacy",
  compare: [
  {
    "label": "Full ingredient quantities on the label",
    "us": true,
    "them": false
  },
  {
    "label": "Plain, unbranded outer packaging",
    "us": true,
    "them": false
  },
  {
    "label": "Pause or cancel without a phone call",
    "us": true,
    "them": false
  },
  {
    "label": "Delivered to your door",
    "us": true,
    "them": true
  }
],
  goals: [],
  spotlightSlug: "",
  promo: {
  "tag": "Limited offer",
  "heading": "[[PLACEHOLDER]] 15% off your first order",
  "text": "[[PLACEHOLDER]] Applies to everything in the range. One use per customer.",
  "code": "WELCOME15",
  "cta": "Shop the offer"
},
  valueProps: [
  {
    "icon": "truck",
    "text": "Free shipping over $50"
  },
  {
    "icon": "box",
    "text": "Plain packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day returns"
  },
  {
    "icon": "chat",
    "text": "Support in 24h"
  }
],
  howItWorks: [
  {
    "title": "Tell us your goal",
    "text": "[[PLACEHOLDER]] Answer a few quick questions so we can point you at the right part of the range."
  },
  {
    "title": "Get matched",
    "text": "[[PLACEHOLDER]] We suggest products that fit what you told us, with the full ingredient list for each."
  },
  {
    "title": "Delivered discreetly",
    "text": "[[PLACEHOLDER]] Your order arrives in plain outer packaging, on a schedule you control."
  }
],
  trustBadges: [
  {
    "icon": "stethoscope",
    "title": "Licensed providers",
    "text": "[[PLACEHOLDER: substantiate before launch]]"
  },
  {
    "icon": "lock",
    "title": "Secure checkout",
    "text": "Payments handled by an encrypted provider."
  },
  {
    "icon": "box",
    "title": "Discreet packaging",
    "text": "Plain outer packaging, no branding outside."
  },
  {
    "icon": "refresh",
    "title": "Money-back guarantee",
    "text": "[[PLACEHOLDER: confirm real terms]]"
  }
],
  productReassurance: [
  {
    "icon": "truck",
    "text": "Free shipping on orders over $50"
  },
  {
    "icon": "box",
    "text": "Plain, unbranded outer packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day return window on unopened items"
  },
  {
    "icon": "lock",
    "text": "Secure checkout"
  }
],
  values: [
  {
    "icon": "shield",
    "title": "Transparent by default",
    "text": "[[PLACEHOLDER]] Full ingredient lists and honest labelling on everything we sell."
  },
  {
    "icon": "stethoscope",
    "title": "Guided by professionals",
    "text": "[[PLACEHOLDER]] Our range is reviewed by qualified practitioners."
  },
  {
    "icon": "leaf",
    "title": "Thoughtfully sourced",
    "text": "[[PLACEHOLDER]] We work with suppliers who meet our quality standards."
  },
  {
    "icon": "chat",
    "title": "Support that answers",
    "text": "[[PLACEHOLDER]] Real people, replying within one business day."
  }
],
  stats: [
  {
    "value": "10k+",
    "label": "[[PLACEHOLDER]] orders delivered"
  },
  {
    "value": "4.8",
    "label": "[[PLACEHOLDER]] average rating"
  },
  {
    "value": "24h",
    "label": "[[PLACEHOLDER]] support response"
  },
  {
    "value": "30d",
    "label": "[[PLACEHOLDER]] returns window"
  }
],
  aboutPoints: [
  "[[PLACEHOLDER]] Every product reviewed before it joins the range",
  "[[PLACEHOLDER]] Clear ingredient lists, no proprietary blends",
  "[[PLACEHOLDER]] Plain packaging on every order",
  "[[PLACEHOLDER]] Cancel or change a subscription at any time"
]
};

/* ==========================================================================
   PRODUCTS
   checkoutUrl is the ONE integration point with your real Shopify store.
   Replace each one with the real product URL, e.g.
     'https://yourstore.com/products/daily-foundation'
   Buttons navigate there in the same tab after firing a tracking event.
   ========================================================================== */

var PRODUCTS = [
  {
    "slug": "daily-foundation",
    "name": "Daily Foundation",
    "sku": "VITALITYRX-DAILYFOUNDAT",
    "category": "Daily essentials",
    "shortBenefit": "A once-a-day base for a routine you will actually keep to.",
    "description": "[[PLACEHOLDER]] A once-a-day base for a routine you will actually keep to. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Foundation from Vitality Rx. A once-a-day base for a routine you will actually keep to.",
    "price": 42,
    "compareAt": 52,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 612,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "One capsule, once a day",
      "Full ingredient list on the label",
      "No proprietary blends"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take as directed on the label as part of your daily routine. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/daily-foundation.svg",
    "gallery": [
      "images/products/daily-foundation.svg",
      "images/products/_angle-daily-essentials-2.svg",
      "images/products/_angle-daily-essentials-3.svg",
      "images/products/_angle-daily-essentials-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Foundation]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-foundation"
  },
  {
    "slug": "evening-wind-down",
    "name": "Evening Wind Down",
    "sku": "VITALITYRX-EVENINGWINDD",
    "category": "Sleep & recovery",
    "shortBenefit": "Formulated to support your evening routine.",
    "description": "[[PLACEHOLDER]] Formulated to support your evening routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Evening Wind Down from Vitality Rx. Formulated to support your evening routine.",
    "price": 38,
    "compareAt": 46,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 431,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Designed for the end of the day",
      "Clearly labelled contents",
      "Comes in a 30-day supply"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Use as directed on the label in the evening. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/evening-wind-down.svg",
    "gallery": [
      "images/products/evening-wind-down.svg",
      "images/products/_angle-sleep-recovery-2.svg",
      "images/products/_angle-sleep-recovery-3.svg",
      "images/products/_angle-sleep-recovery-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Evening Wind Down]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/evening-wind-down"
  },
  {
    "slug": "focus-support",
    "name": "Focus Support",
    "sku": "VITALITYRX-FOCUSSUPPORT",
    "category": "Daily essentials",
    "shortBenefit": "Made for the middle of a long day.",
    "description": "[[PLACEHOLDER]] Made for the middle of a long day. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Focus Support from Vitality Rx. Made for the middle of a long day.",
    "price": 46,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.6,
    "reviewCount": 288,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Convenient daily format",
      "Transparent labelling",
      "Fits alongside the rest of the range"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take as directed on the label. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/focus-support.svg",
    "gallery": [
      "images/products/focus-support.svg",
      "images/products/_angle-daily-essentials-2.svg",
      "images/products/_angle-daily-essentials-3.svg",
      "images/products/_angle-daily-essentials-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Focus Support]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/focus-support"
  },
  {
    "slug": "hair-thickening-serum",
    "name": "Thickening Serum",
    "sku": "VITALITYRX-HAIRTHICKENI",
    "category": "Hair & skin",
    "shortBenefit": "A daily topical step for your routine.",
    "description": "[[PLACEHOLDER]] A daily topical step for your routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Thickening Serum from Vitality Rx. A daily topical step for your routine.",
    "price": 54,
    "compareAt": 68,
    "priceNote": "per 30-day supply",
    "rating": 4.5,
    "reviewCount": 356,
    "badge": "New",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Lightweight, non-greasy formula",
      "Applied once daily",
      "Unscented"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Apply to clean, dry skin as directed on the label. Patch test before first use.",
    "image": "images/products/hair-thickening-serum.svg",
    "gallery": [
      "images/products/hair-thickening-serum.svg",
      "images/products/_angle-hair-skin-2.svg",
      "images/products/_angle-hair-skin-3.svg",
      "images/products/_angle-hair-skin-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Thickening Serum]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/hair-thickening-serum"
  },
  {
    "slug": "post-training-recovery",
    "name": "Post-Training Recovery",
    "sku": "VITALITYRX-POSTTRAINING",
    "category": "Sleep & recovery",
    "shortBenefit": "Built into the part of the day you already plan around.",
    "description": "[[PLACEHOLDER]] Built into the part of the day you already plan around. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Post-Training Recovery from Vitality Rx. Built into the part of the day you already plan around.",
    "price": 44,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 197,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Mixes into water or a shake",
      "Unflavoured option available",
      "30 servings per tub"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Mix one serving as directed on the label. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/post-training-recovery.svg",
    "gallery": [
      "images/products/post-training-recovery.svg",
      "images/products/_angle-sleep-recovery-2.svg",
      "images/products/_angle-sleep-recovery-3.svg",
      "images/products/_angle-sleep-recovery-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Post-Training Recovery]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/post-training-recovery"
  },
  {
    "slug": "starter-bundle",
    "name": "The Starter Bundle",
    "sku": "VITALITYRX-STARTERBUNDL",
    "category": "Bundles",
    "shortBenefit": "Three of the range together, at a lower price than buying separately.",
    "description": "[[PLACEHOLDER]] Three of the range together, at a lower price than buying separately. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Starter Bundle from Vitality Rx. Three of the range together, at a lower price than buying separately.",
    "price": 96,
    "compareAt": 126,
    "priceNote": "one-off purchase",
    "rating": 4.9,
    "reviewCount": 143,
    "badge": "Save 24%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Daily Foundation, Focus Support and Evening Wind Down",
      "One delivery instead of three",
      "Cancel or change at any time"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the label directions for each product in the bundle.",
    "image": "images/products/starter-bundle.svg",
    "gallery": [
      "images/products/starter-bundle.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Starter Bundle]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/starter-bundle"
  }
];

/* ========================================================================== */

var TESTIMONIALS = [
  {
    "name": "Daniel R.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] Ordering was simple and it turned up faster than I expected. The packaging was completely plain, which I appreciated."
  },
  {
    "name": "Marcus T.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] I like that the label actually tells you what is in it. No mystery blend, no fine print I needed a magnifying glass for."
  },
  {
    "name": "Omar J.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 4,
    "quote": "[[PLACEHOLDER]] Support answered my question the same day. Straightforward to reorder when I ran low."
  }
];

var FAQS = [
  {
    "q": "How do I place an order?",
    "a": "[[PLACEHOLDER]] Choose the product you want and select Buy now. You will be taken to our secure store to complete checkout."
  },
  {
    "q": "How long does delivery take?",
    "a": "[[PLACEHOLDER: confirm real timings]] Orders are usually prepared for dispatch within a couple of business days. Delivery estimates are shown at checkout."
  },
  {
    "q": "Is the packaging discreet?",
    "a": "[[PLACEHOLDER]] Yes. Orders arrive in plain outer packaging with no product branding on the outside."
  },
  {
    "q": "Can I return something?",
    "a": "[[PLACEHOLDER: confirm real policy]] Unopened items can be returned within the window shown at checkout. Some health and personal care items cannot be returned once opened."
  },
  {
    "q": "Do you offer a subscription?",
    "a": "[[PLACEHOLDER]] Where a repeat option is available it is shown on the product page at checkout, and you can change or cancel it at any time."
  },
  {
    "q": "Should I speak to a healthcare professional first?",
    "a": "[[PLACEHOLDER]] If you are pregnant or breastfeeding, take prescription medicine, or have an existing medical condition, speak to a qualified healthcare professional before starting anything new. See our medical disclaimer."
  },
  {
    "q": "How do I contact support?",
    "a": "[[PLACEHOLDER]] Use the contact form, or email us directly. We aim to reply within one business day."
  },
  {
    "q": "Where do you ship?",
    "a": "[[PLACEHOLDER: list real destinations]] Shipping destinations and rates are shown at checkout."
  }
];
