/* ==========================================================================
   BRAND-CONFIG.JS — Lunelle Silk

   >>> THIS IS THE ONLY FILE YOU NEED TO EDIT. <<<

   Everything below drives the whole site: brand name, colours, products,
   prices, testimonials, FAQs, and the Shopify redirect links.

   TO GO LIVE, YOU MUST:
     1. Replace every checkoutUrl with the real Shopify product URL.
     2. Replace every [[PLACEHOLDER: ...]] string.
     3. Replace the images in images/ and images/products/ with real photos.
     4. Add real tracking IDs below and set tracking.enabled to true.
     5. Remove the noindex tag from every .html file (search for "noindex").

   Find every remaining placeholder at once:
     grep -rn "PLACEHOLDER" .           (Mac/Linux)
     findstr /s /n "PLACEHOLDER" *.*    (Windows)
   ========================================================================== */

var BRAND = {
  name: "Lunelle Silk",
  tagline: "A little silk. A lot to love.",
  announcement: "[[PLACEHOLDER]] Buy 3, get 1 free — ends Sunday",
  logo: 'images/logo.svg',

  /* ---- Colours. theme-init.js applies these before first paint. -------- */
  colors: {
  "background": "#ffffff",
  "surface": "#f7f8fb",
  "soft": "#f1f3f9",
  "text": "#2b3244",
  "heading": "#111a2e",
  "muted": "#6b7488",
  "border": "#e5e8f0",
  "borderStrong": "#c9cfdd",
  "accent": "#1b2a4e",
  "accentHover": "#111d3a",
  "accentTint": "#e9edf6",
  "onAccent": "#ffffff",
  "accentDeep": "#16233f",
  "accentDeeper": "#0c1630",
  "accentAlt": "#c0563c",
  "accentAltTint": "#fbeee9",
  "footerBg": "#111a2e",
  "footerText": "#c3c9d8",
  "star": "#dfa93f"
},

  style: {
  "radius": "14px",
  "radiusLarge": "22px",
  "buttonRadius": "999px",
  "cardStyle": "bordered",
  "logoWidth": "156px"
},

  currency: {
  "symbol": "$",
  "code": "USD",
  "decimals": 2
},

  /* Every category has its own page. Generated by _tools/generate.js. */
  categoryPages: {
  "Pillowcases": "pillowcases.html",
  "Sleep Masks": "sleep-masks.html",
  "Scrunchies": "scrunchies.html",
  "Bundles": "bundles.html"
},
  /* Rendered into the footer, so removing a legal page cannot leave a dead link. */
  legalPages: [
  {
    "title": "Privacy Policy",
    "href": "privacy-policy.html"
  },
  {
    "title": "Terms of Service",
    "href": "terms-of-service.html"
  },
  {
    "title": "Shipping & Refund Policy",
    "href": "shipping-refund-policy.html"
  }
],
  categoryIndex: {
  "Pillowcases": 1,
  "Sleep Masks": 2,
  "Scrunchies": 3,
  "Bundles": 4
},
  categoryIcons: {
  "Pillowcases": "leaf",
  "Sleep Masks": "clock",
  "Scrunchies": "refresh",
  "Bundles": "box"
},

  contact: {
    email: "hello@lunelle-placeholder.com",
    phone: "+1 (555) 010-7788",
    hours: "Mon–Sat, 9am–7pm",
    address: "[[PLACEHOLDER: registered business address]]",
    legalEntity: "Lunelle Silk Ltd"
  },

  /* ---- Footer health disclaimer. Ad reviewers read this. --------------- */
  disclaimer: "[[PLACEHOLDER: health disclaimer]] The content on this site is for general information only and is not medical advice. Always speak to a qualified healthcare professional before starting, stopping or changing anything related to your health. Products are not intended to diagnose, treat, cure or prevent any disease.",

  copy: {
    buyCta: 'Buy now'
  },

  /* ---- Ad pixels. Nothing loads or fires until enabled is true. -------- */
  tracking: {
    enabled: false,
    ga4MeasurementId: '',            // 'G-XXXXXXXXXX'
    googleAdsConversionId: '',       // 'AW-XXXXXXXXX'
    googleAdsConversionLabel: '',    // the label from the conversion action
    metaPixelId: ''                  // numeric ID only
  },

  seo: {
    /* Leave false until a real review app supplies ratings. Invented ratings
       in structured data get Merchant Center accounts suspended. */
    emitAggregateRating: false
  },

  heroProof: [
  "Free delivery over $75",
  "60-night trial",
  "Gift-boxed"
],
  marquee: [
  "Free delivery over $75",
  "60-night trial",
  "22-momme mulberry silk",
  "Silk on both sides",
  "Gift-boxed as standard",
  "Machine washable",
  "Buy 3, get 1 free"
],
  goals: [],
  heroProducts: [
  "silk-pillowcase-champagne",
  "silk-pillowcase-blush",
  "silk-pillowcase-midnight"
],
  awards: [
  {
    "value": "230,000+",
    "label": "[[PLACEHOLDER]] 5-star reviews"
  },
  {
    "value": "2023–25",
    "label": "[[PLACEHOLDER]] Most gifted, three years"
  },
  {
    "value": "22",
    "label": "Momme mulberry silk"
  },
  {
    "value": "60",
    "label": "Night trial"
  }
],
  press: [
  "[[PLACEHOLDER]] VOGUE",
  "FORBES",
  "ELLE",
  "GQ",
  "HARPER&rsquo;S",
  "ALLURE"
],
  newArrivals: [
  "silk-pillowcase-sage",
  "silk-pillowcase-lavender",
  "silk-pillowcase-gold"
],
  qualityPicks: [
  "silk-pillowcase-champagne",
  "the-sleep-set",
  "silk-sleep-mask-champagne"
],
  spotlightSlug: "silk-pillowcase-champagne",
  promo: {
  "tag": "This week",
  "heading": "[[PLACEHOLDER]] Buy 3, get 1 free",
  "text": "[[PLACEHOLDER]] Mix any colours and any sizes. The cheapest of the four comes off at checkout.",
  "code": "SILK4",
  "cta": "Shop the offer"
},
  valueProps: [
  {
    "icon": "truck",
    "text": "Free delivery over $75"
  },
  {
    "icon": "box",
    "text": "Gift-boxed as standard"
  },
  {
    "icon": "refresh",
    "text": "60-night trial"
  },
  {
    "icon": "chat",
    "text": "Support in 24h"
  }
],
  howItWorks: [
  {
    "title": "Pick your colour",
    "text": "[[PLACEHOLDER]] Ten silk colours, three sizes. Swatches on every product page."
  },
  {
    "title": "We box it up",
    "text": "[[PLACEHOLDER]] Gift box and ribbon as standard, note optional at checkout."
  },
  {
    "title": "Sleep on it",
    "text": "[[PLACEHOLDER]] Sixty nights to decide. Send it back if it is not for you."
  }
],
  trustBadges: [
  {
    "icon": "stethoscope",
    "title": "Licensed providers",
    "text": "[[PLACEHOLDER: substantiate before launch]]"
  },
  {
    "icon": "lock",
    "title": "Secure checkout",
    "text": "Payments handled by an encrypted provider."
  },
  {
    "icon": "box",
    "title": "Discreet packaging",
    "text": "Plain outer packaging, no branding outside."
  },
  {
    "icon": "refresh",
    "title": "Money-back guarantee",
    "text": "[[PLACEHOLDER: confirm real terms]]"
  }
],
  productReassurance: [
  {
    "icon": "truck",
    "text": "Free shipping on orders over $50"
  },
  {
    "icon": "box",
    "text": "Plain, unbranded outer packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day return window on unopened items"
  },
  {
    "icon": "lock",
    "text": "Secure checkout"
  }
],
  values: [
  {
    "icon": "shield",
    "title": "Transparent by default",
    "text": "[[PLACEHOLDER]] Full ingredient lists and honest labelling on everything we sell."
  },
  {
    "icon": "stethoscope",
    "title": "Guided by professionals",
    "text": "[[PLACEHOLDER]] Our range is reviewed by qualified practitioners."
  },
  {
    "icon": "leaf",
    "title": "Thoughtfully sourced",
    "text": "[[PLACEHOLDER]] We work with suppliers who meet our quality standards."
  },
  {
    "icon": "chat",
    "title": "Support that answers",
    "text": "[[PLACEHOLDER]] Real people, replying within one business day."
  }
],
  stats: [
  {
    "value": "10k+",
    "label": "[[PLACEHOLDER]] orders delivered"
  },
  {
    "value": "4.8",
    "label": "[[PLACEHOLDER]] average rating"
  },
  {
    "value": "24h",
    "label": "[[PLACEHOLDER]] support response"
  },
  {
    "value": "30d",
    "label": "[[PLACEHOLDER]] returns window"
  }
],
  aboutPoints: [
  "[[PLACEHOLDER]] Every product reviewed before it joins the range",
  "[[PLACEHOLDER]] Clear ingredient lists, no proprietary blends",
  "[[PLACEHOLDER]] Plain packaging on every order",
  "[[PLACEHOLDER]] Cancel or change a subscription at any time"
]
};

/* ==========================================================================
   PRODUCTS
   checkoutUrl is the ONE integration point with your real Shopify store.
   Replace each one with the real product URL, e.g.
     'https://yourstore.com/products/daily-foundation'
   Buttons navigate there in the same tab after firing a tracking event.
   ========================================================================== */

var PRODUCTS = [
  {
    "slug": "silk-pillowcase-champagne",
    "name": "Silk Pillowcase — Champagne",
    "sku": "EVERWELL-SILKPILLOWCA",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Champagne from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 4820,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 100% mulberry silk, 22 momme",
      "[[PLACEHOLDER]] Hidden zip, silk on both sides",
      "[[PLACEHOLDER]] Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "[[PLACEHOLDER]] Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-champagne.svg",
    "gallery": [
      "images/products/silk-pillowcase-champagne.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Champagne]]",
    "swatch": "#e8dcc6",
    "colour": "Champagne",
    "tint": "#fcfaf7",
    "deep": "#686359",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-pillowcase-champagne"
  },
  {
    "slug": "silk-pillowcase-ivory",
    "name": "Silk Pillowcase — Ivory",
    "sku": "EVERWELL-SILKPILLOWCA",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Ivory from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 3140,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 100% mulberry silk, 22 momme",
      "[[PLACEHOLDER]] Hidden zip, silk on both sides",
      "[[PLACEHOLDER]] Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "[[PLACEHOLDER]] Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-ivory.svg",
    "gallery": [
      "images/products/silk-pillowcase-ivory.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Ivory]]",
    "swatch": "#f2ece1",
    "colour": "Ivory",
    "tint": "#fdfcfb",
    "deep": "#6d6a65",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-pillowcase-ivory"
  },
  {
    "slug": "silk-pillowcase-blush",
    "name": "Silk Pillowcase — Blush",
    "sku": "EVERWELL-SILKPILLOWCA",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Blush from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 2760,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 100% mulberry silk, 22 momme",
      "[[PLACEHOLDER]] Hidden zip, silk on both sides",
      "[[PLACEHOLDER]] Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "[[PLACEHOLDER]] Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-blush.svg",
    "gallery": [
      "images/products/silk-pillowcase-blush.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Blush]]",
    "swatch": "#edd3d1",
    "colour": "Blush",
    "tint": "#fcf9f9",
    "deep": "#6b5f5e",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-pillowcase-blush"
  },
  {
    "slug": "silk-pillowcase-midnight",
    "name": "Silk Pillowcase — Midnight",
    "sku": "EVERWELL-SILKPILLOWCA",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Midnight from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 2210,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 100% mulberry silk, 22 momme",
      "[[PLACEHOLDER]] Hidden zip, silk on both sides",
      "[[PLACEHOLDER]] Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "[[PLACEHOLDER]] Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-midnight.svg",
    "gallery": [
      "images/products/silk-pillowcase-midnight.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Midnight]]",
    "swatch": "#2a3350",
    "colour": "Midnight",
    "tint": "#e1e2e7",
    "deep": "#131724",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-pillowcase-midnight"
  },
  {
    "slug": "silk-pillowcase-sage",
    "name": "Silk Pillowcase — Sage",
    "sku": "EVERWELL-SILKPILLOWCA",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Sage from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 1180,
    "badge": "New",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 100% mulberry silk, 22 momme",
      "[[PLACEHOLDER]] Hidden zip, silk on both sides",
      "[[PLACEHOLDER]] Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "[[PLACEHOLDER]] Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-sage.svg",
    "gallery": [
      "images/products/silk-pillowcase-sage.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Sage]]",
    "swatch": "#cdd8c8",
    "colour": "Sage",
    "tint": "#f8faf7",
    "deep": "#5c615a",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-pillowcase-sage"
  },
  {
    "slug": "silk-pillowcase-lavender",
    "name": "Silk Pillowcase — Lavender",
    "sku": "EVERWELL-SILKPILLOWCA",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Lavender from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 960,
    "badge": "New",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 100% mulberry silk, 22 momme",
      "[[PLACEHOLDER]] Hidden zip, silk on both sides",
      "[[PLACEHOLDER]] Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "[[PLACEHOLDER]] Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-lavender.svg",
    "gallery": [
      "images/products/silk-pillowcase-lavender.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Lavender]]",
    "swatch": "#d8d2e6",
    "colour": "Lavender",
    "tint": "#faf9fc",
    "deep": "#615e67",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-pillowcase-lavender"
  },
  {
    "slug": "silk-pillowcase-pearl",
    "name": "Silk Pillowcase — Pearl",
    "sku": "EVERWELL-SILKPILLOWCA",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Pearl from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 1540,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 100% mulberry silk, 22 momme",
      "[[PLACEHOLDER]] Hidden zip, silk on both sides",
      "[[PLACEHOLDER]] Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "[[PLACEHOLDER]] Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-pearl.svg",
    "gallery": [
      "images/products/silk-pillowcase-pearl.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Pearl]]",
    "swatch": "#e4e6ea",
    "colour": "Pearl",
    "tint": "#fbfcfc",
    "deep": "#676769",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-pillowcase-pearl"
  },
  {
    "slug": "silk-pillowcase-gold",
    "name": "Silk Pillowcase — Gold",
    "sku": "EVERWELL-SILKPILLOWCA",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Gold from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 99,
    "compareAt": 124,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 870,
    "badge": "New",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 100% mulberry silk, 22 momme",
      "[[PLACEHOLDER]] Hidden zip, silk on both sides",
      "[[PLACEHOLDER]] Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "[[PLACEHOLDER]] Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-gold.svg",
    "gallery": [
      "images/products/silk-pillowcase-gold.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Gold]]",
    "swatch": "#dfc68c",
    "colour": "Gold",
    "tint": "#fbf7ef",
    "deep": "#64593f",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-pillowcase-gold"
  },
  {
    "slug": "silk-sleep-mask-champagne",
    "name": "Silk Sleep Mask — Champagne",
    "sku": "EVERWELL-SILKSLEEPMAS",
    "category": "Sleep Masks",
    "shortBenefit": "Blocks the light, adjustable strap.",
    "description": "[[PLACEHOLDER]] Blocks the light, adjustable strap. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Champagne from Lunelle Silk. Blocks the light, adjustable strap.",
    "price": 39,
    "compareAt": 49,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 1420,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 22-momme mulberry silk",
      "[[PLACEHOLDER]] Adjustable, no-snag strap",
      "[[PLACEHOLDER]] Travel pouch included"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk"
    ],
    "howItWorks": "[[PLACEHOLDER]] Adjust the strap and wear it over the eyes. Hand wash cool.",
    "image": "images/products/silk-sleep-mask-champagne.svg",
    "gallery": [
      "images/products/silk-sleep-mask-champagne.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Champagne]]",
    "swatch": "#e8dcc6",
    "colour": "Champagne",
    "tint": "#fcfaf7",
    "deep": "#686359",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-sleep-mask-champagne"
  },
  {
    "slug": "silk-sleep-mask-midnight",
    "name": "Silk Sleep Mask — Midnight",
    "sku": "EVERWELL-SILKSLEEPMAS",
    "category": "Sleep Masks",
    "shortBenefit": "Blocks the light, adjustable strap.",
    "description": "[[PLACEHOLDER]] Blocks the light, adjustable strap. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Midnight from Lunelle Silk. Blocks the light, adjustable strap.",
    "price": 39,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 980,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] 22-momme mulberry silk",
      "[[PLACEHOLDER]] Adjustable, no-snag strap",
      "[[PLACEHOLDER]] Travel pouch included"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk"
    ],
    "howItWorks": "[[PLACEHOLDER]] Adjust the strap and wear it over the eyes. Hand wash cool.",
    "image": "images/products/silk-sleep-mask-midnight.svg",
    "gallery": [
      "images/products/silk-sleep-mask-midnight.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Midnight]]",
    "swatch": "#2a3350",
    "colour": "Midnight",
    "tint": "#e1e2e7",
    "deep": "#131724",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-sleep-mask-midnight"
  },
  {
    "slug": "silk-scrunchies-neutrals",
    "name": "Silk Scrunchies — Neutrals",
    "sku": "EVERWELL-SILKSCRUNCHI",
    "category": "Scrunchies",
    "shortBenefit": "Set of three, no-crease.",
    "description": "[[PLACEHOLDER]] Set of three, no-crease. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Neutrals from Lunelle Silk. Set of three, no-crease.",
    "price": 29,
    "compareAt": 36,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 2310,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] Three scrunchies per set",
      "[[PLACEHOLDER]] Soft elastic, holds without pulling",
      "[[PLACEHOLDER]] 22-momme mulberry silk"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] Covered elastic"
    ],
    "howItWorks": "[[PLACEHOLDER]] Wear as you would any hair tie. Hand wash cool.",
    "image": "images/products/silk-scrunchies-neutrals.svg",
    "gallery": [
      "images/products/silk-scrunchies-neutrals.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Neutrals]]",
    "swatch": "#f2ece1",
    "colour": "Neutrals",
    "tint": "#fdfcfb",
    "deep": "#6d6a65",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-scrunchies-neutrals"
  },
  {
    "slug": "silk-scrunchies-jewels",
    "name": "Silk Scrunchies — Jewels",
    "sku": "EVERWELL-SILKSCRUNCHI",
    "category": "Scrunchies",
    "shortBenefit": "Set of three, no-crease.",
    "description": "[[PLACEHOLDER]] Set of three, no-crease. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Jewels from Lunelle Silk. Set of three, no-crease.",
    "price": 29,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 1160,
    "badge": "New",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] Three scrunchies per set",
      "[[PLACEHOLDER]] Soft elastic, holds without pulling",
      "[[PLACEHOLDER]] 22-momme mulberry silk"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] Covered elastic"
    ],
    "howItWorks": "[[PLACEHOLDER]] Wear as you would any hair tie. Hand wash cool.",
    "image": "images/products/silk-scrunchies-jewels.svg",
    "gallery": [
      "images/products/silk-scrunchies-jewels.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Jewels]]",
    "swatch": "#d8d2e6",
    "colour": "Jewels",
    "tint": "#faf9fc",
    "deep": "#615e67",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-scrunchies-jewels"
  },
  {
    "slug": "the-sleep-set",
    "name": "The Sleep Set",
    "sku": "EVERWELL-THESLEEPSET",
    "category": "Bundles",
    "shortBenefit": "Pillowcase, sleep mask and scrunchies.",
    "description": "[[PLACEHOLDER]] Pillowcase, sleep mask and scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Sleep Set from Lunelle Silk. Pillowcase, sleep mask and scrunchies.",
    "price": 139,
    "compareAt": 179,
    "priceNote": "one-off purchase",
    "rating": 4.9,
    "reviewCount": 1640,
    "badge": "Save 22%",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] One pillowcase, one mask, one scrunchie set",
      "[[PLACEHOLDER]] Arrives gift-boxed",
      "[[PLACEHOLDER]] Cheaper than buying separately"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk throughout"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the care label on each piece. Wash cool, hang to dry.",
    "image": "images/products/the-sleep-set.svg",
    "gallery": [
      "images/products/the-sleep-set.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Sleep Set]]",
    "swatch": "#e2b8b8",
    "colour": "Blush",
    "tint": "#fbf5f5",
    "deep": "#665353",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/the-sleep-set"
  },
  {
    "slug": "the-pillowcase-pair",
    "name": "The Pillowcase Pair",
    "sku": "EVERWELL-THEPILLOWCAS",
    "category": "Bundles",
    "shortBenefit": "Two pillowcases, one for each side.",
    "description": "[[PLACEHOLDER]] Two pillowcases, one for each side. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Pillowcase Pair from Lunelle Silk. Two pillowcases, one for each side.",
    "price": 159,
    "compareAt": 198,
    "priceNote": "one-off purchase",
    "rating": 4.9,
    "reviewCount": 920,
    "badge": "Buy 3 get 1",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] Two 22-momme pillowcases",
      "[[PLACEHOLDER]] Mix or match the colours",
      "[[PLACEHOLDER]] Arrives gift-boxed"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk"
    ],
    "howItWorks": "[[PLACEHOLDER]] Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/the-pillowcase-pair.svg",
    "gallery": [
      "images/products/the-pillowcase-pair.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Pillowcase Pair]]",
    "swatch": "#e4e6ea",
    "colour": "Pearl",
    "tint": "#fbfcfc",
    "deep": "#676769",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/the-pillowcase-pair"
  },
  {
    "slug": "the-gift-box",
    "name": "The Gift Box",
    "sku": "EVERWELL-THEGIFTBOX",
    "category": "Bundles",
    "shortBenefit": "The whole range, boxed and ribboned.",
    "description": "[[PLACEHOLDER]] The whole range, boxed and ribboned. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Gift Box from Lunelle Silk. The whole range, boxed and ribboned.",
    "price": 199,
    "compareAt": 254,
    "priceNote": "one-off purchase",
    "rating": 5,
    "reviewCount": 540,
    "badge": "Save 22%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "[[PLACEHOLDER]] Pillowcase, mask, scrunchies and a travel pouch",
      "[[PLACEHOLDER]] Gift box and ribbon included",
      "[[PLACEHOLDER]] Add a handwritten note at checkout"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk throughout"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the care label on each piece.",
    "image": "images/products/the-gift-box.svg",
    "gallery": [
      "images/products/the-gift-box.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Gift Box]]",
    "swatch": "#dfc68c",
    "colour": "Gold",
    "tint": "#fbf7ef",
    "deep": "#64593f",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/the-gift-box"
  }
];

/* ========================================================================== */

var TESTIMONIALS = [
  {
    "name": "Amelia R.",
    "role": "[[PLACEHOLDER]] Verified buyer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] I bought one to try and ordered three more the same week. My hair is noticeably less of a mess in the morning.",
    "avatar": "images/avatars/avatar-1.svg"
  },
  {
    "name": "Priya S.",
    "role": "[[PLACEHOLDER]] Verified buyer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] It washes beautifully. Six months in and the champagne one still looks like it did on day one.",
    "avatar": "images/avatars/avatar-2.svg"
  },
  {
    "name": "Daniel K.",
    "role": "[[PLACEHOLDER]] Verified buyer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] Bought the midnight as a gift and ended up keeping it. Ordered two more.",
    "avatar": "images/avatars/avatar-3.svg"
  },
  {
    "name": "Hana M.",
    "role": "[[PLACEHOLDER]] Verified buyer",
    "rating": 4,
    "quote": "[[PLACEHOLDER]] The zip is the detail that sold me — nothing slides off in the night.",
    "avatar": "images/avatars/avatar-4.svg"
  },
  {
    "name": "Grace L.",
    "role": "[[PLACEHOLDER]] Verified buyer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] The gift box arrived looking genuinely expensive. I did not need to wrap anything.",
    "avatar": "images/avatars/avatar-5.svg"
  },
  {
    "name": "Sofia T.",
    "role": "[[PLACEHOLDER]] Verified buyer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] Sleep mask and pillowcase in the same colour. Small thing, but it looks considered.",
    "avatar": "images/avatars/avatar-6.svg"
  },
  {
    "name": "Noor A.",
    "role": "[[PLACEHOLDER]] Verified buyer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] Delivery was quicker than the estimate and the packaging was lovely.",
    "avatar": "images/avatars/avatar-7.svg"
  },
  {
    "name": "Elena V.",
    "role": "[[PLACEHOLDER]] Verified buyer",
    "rating": 4,
    "quote": "[[PLACEHOLDER]] I was sceptical about the price. Having slept on it for a month, I get it now.",
    "avatar": "images/avatars/avatar-8.svg"
  }
];

/* Shown above the reviews. Replace with real aggregate numbers, or delete the
   block from index.html — invented ratings must not reach structured data. */
var REVIEWS_SUMMARY = {
  "rating": 4.9,
  "count": "[[PLACEHOLDER: 230,000]]",
  "promo": {
    "pill": "Award",
    "text": "[[PLACEHOLDER]] Most gifted product three years running —",
    "linkText": "Read all reviews",
    "href": "shop.html"
  }
};

var FAQS = [
  {
    "q": "How do I place an order?",
    "a": "[[PLACEHOLDER]] Choose the product you want and select Buy now. You will be taken to our secure store to complete checkout."
  },
  {
    "q": "How long does delivery take?",
    "a": "[[PLACEHOLDER: confirm real timings]] Orders are usually prepared for dispatch within a couple of business days. Delivery estimates are shown at checkout."
  },
  {
    "q": "Is the packaging discreet?",
    "a": "[[PLACEHOLDER]] Yes. Orders arrive in plain outer packaging with no product branding on the outside."
  },
  {
    "q": "Can I return something?",
    "a": "[[PLACEHOLDER: confirm real policy]] Unopened items can be returned within the window shown at checkout. Some health and personal care items cannot be returned once opened."
  },
  {
    "q": "Do you offer a subscription?",
    "a": "[[PLACEHOLDER]] Where a repeat option is available it is shown on the product page at checkout, and you can change or cancel it at any time."
  },
  {
    "q": "Should I speak to a healthcare professional first?",
    "a": "[[PLACEHOLDER]] If you are pregnant or breastfeeding, take prescription medicine, or have an existing medical condition, speak to a qualified healthcare professional before starting anything new. See our medical disclaimer."
  },
  {
    "q": "How do I contact support?",
    "a": "[[PLACEHOLDER]] Use the contact form, or email us directly. We aim to reply within one business day."
  },
  {
    "q": "Where do you ship?",
    "a": "[[PLACEHOLDER: list real destinations]] Shipping destinations and rates are shown at checkout."
  }
];
