/* ==========================================================================
   BRAND-CONFIG.JS — Everwell

   >>> THIS IS THE ONLY FILE YOU NEED TO EDIT. <<<

   Everything below drives the whole site: brand name, colours, products,
   prices, testimonials, FAQs, and the Shopify redirect links.

   TO GO LIVE, YOU MUST:
     1. Replace every checkoutUrl with the real Shopify product URL.
     2. Replace every [[PLACEHOLDER: ...]] string.
     3. Replace the images in images/ and images/products/ with real photos.
     4. Add real tracking IDs below and set tracking.enabled to true.
     5. Remove the noindex tag from every .html file (search for "noindex").

   Find every remaining placeholder at once:
     grep -rn "PLACEHOLDER" .           (Mac/Linux)
     findstr /s /n "PLACEHOLDER" *.*    (Windows)
   ========================================================================== */

var BRAND = {
  name: "Everwell",
  tagline: "Everyday health essentials, all in one place.",
  announcement: "Free discreet shipping on orders over $50",
  logo: 'images/logo.svg',

  /* ---- Colours. theme-init.js applies these before first paint. -------- */
  colors: {
  "background": "#ffffff",
  "surface": "#f4f7f8",
  "soft": "#eff4f5",
  "text": "#132228",
  "heading": "#0d1a1f",
  "muted": "#5b6d74",
  "border": "#dde7e9",
  "borderStrong": "#c2d1d4",
  "accent": "#0e6f6c",
  "accentHover": "#0a5451",
  "accentTint": "#e3f0ef",
  "onAccent": "#ffffff",
  "footerBg": "#0d1a1f",
  "footerText": "#c3d3d6",
  "star": "#e0a12c"
},

  style: {
  "radius": "14px",
  "radiusLarge": "18px",
  "buttonRadius": "999px",
  "cardStyle": "bordered",
  "logoWidth": "152px"
},

  currency: {
  "symbol": "$",
  "code": "USD",
  "decimals": 2
},

  /* Every category has its own page. Generated by _tools/generate.js. */
  categoryPages: {
  "Men's Health": "mens-health.html",
  "Skincare": "skincare.html",
  "Weight Management": "weight-management.html",
  "Daily Supplements": "daily-supplements.html",
  "Sleep & Calm": "sleep-calm.html",
  "Bundles": "bundles.html"
},
  categoryIcons: {
  "Men's Health": "user",
  "Skincare": "leaf",
  "Weight Management": "refresh",
  "Daily Supplements": "shield",
  "Sleep & Calm": "clock",
  "Bundles": "box"
},

  contact: {
    email: "support@everwell-placeholder.com",
    phone: "+1 (555) 010-3300",
    hours: "Mon–Sat, 8am–7pm ET",
    address: "[[PLACEHOLDER: registered business address]]",
    legalEntity: "Everwell Health Ltd"
  },

  /* ---- Footer health disclaimer. Ad reviewers read this. --------------- */
  disclaimer: "[[PLACEHOLDER: health disclaimer]] The content on this site is for general information only and is not medical advice. Always speak to a qualified healthcare professional before starting, stopping or changing anything related to your health. Products are not intended to diagnose, treat, cure or prevent any disease.",

  copy: {
    buyCta: 'Buy now'
  },

  /* ---- Ad pixels. Nothing loads or fires until enabled is true. -------- */
  tracking: {
    enabled: false,
    ga4MeasurementId: '',            // 'G-XXXXXXXXXX'
    googleAdsConversionId: '',       // 'AW-XXXXXXXXX'
    googleAdsConversionLabel: '',    // the label from the conversion action
    metaPixelId: ''                  // numeric ID only
  },

  seo: {
    /* Leave false until a real review app supplies ratings. Invented ratings
       in structured data get Merchant Center accounts suspended. */
    emitAggregateRating: false
  },

  heroProof: [
  "Licensed providers",
  "Discreet packaging",
  "Cancel anytime"
],
  valueProps: [
  {
    "icon": "truck",
    "text": "Free shipping over $50"
  },
  {
    "icon": "box",
    "text": "Plain packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day returns"
  },
  {
    "icon": "chat",
    "text": "Support in 24h"
  }
],
  howItWorks: [
  {
    "title": "Find what you need",
    "text": "[[PLACEHOLDER]] Browse by category, or answer a few questions and we will point you at the right shelf."
  },
  {
    "title": "Check out securely",
    "text": "[[PLACEHOLDER]] One basket for everything, however many categories you are buying from."
  },
  {
    "title": "Delivered discreetly",
    "text": "[[PLACEHOLDER]] Plain outer packaging, on a schedule you control."
  }
],
  trustBadges: [
  {
    "icon": "stethoscope",
    "title": "Licensed providers",
    "text": "[[PLACEHOLDER: substantiate before launch]]"
  },
  {
    "icon": "lock",
    "title": "Secure checkout",
    "text": "Payments handled by an encrypted provider."
  },
  {
    "icon": "box",
    "title": "Discreet packaging",
    "text": "Plain outer packaging, no branding outside."
  },
  {
    "icon": "refresh",
    "title": "Money-back guarantee",
    "text": "[[PLACEHOLDER: confirm real terms]]"
  }
],
  productReassurance: [
  {
    "icon": "truck",
    "text": "Free shipping on orders over $50"
  },
  {
    "icon": "box",
    "text": "Plain, unbranded outer packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day return window on unopened items"
  },
  {
    "icon": "lock",
    "text": "Secure checkout"
  }
],
  values: [
  {
    "icon": "shield",
    "title": "Transparent by default",
    "text": "[[PLACEHOLDER]] Full ingredient lists and honest labelling on everything we sell."
  },
  {
    "icon": "stethoscope",
    "title": "Guided by professionals",
    "text": "[[PLACEHOLDER]] Our range is reviewed by qualified practitioners."
  },
  {
    "icon": "leaf",
    "title": "Thoughtfully sourced",
    "text": "[[PLACEHOLDER]] We work with suppliers who meet our quality standards."
  },
  {
    "icon": "chat",
    "title": "Support that answers",
    "text": "[[PLACEHOLDER]] Real people, replying within one business day."
  }
],
  stats: [
  {
    "value": "10k+",
    "label": "[[PLACEHOLDER]] orders delivered"
  },
  {
    "value": "4.8",
    "label": "[[PLACEHOLDER]] average rating"
  },
  {
    "value": "24h",
    "label": "[[PLACEHOLDER]] support response"
  },
  {
    "value": "30d",
    "label": "[[PLACEHOLDER]] returns window"
  }
],
  aboutPoints: [
  "[[PLACEHOLDER]] Every product reviewed before it joins the range",
  "[[PLACEHOLDER]] Clear ingredient lists, no proprietary blends",
  "[[PLACEHOLDER]] Plain packaging on every order",
  "[[PLACEHOLDER]] Cancel or change a subscription at any time"
]
};

/* ==========================================================================
   PRODUCTS
   checkoutUrl is the ONE integration point with your real Shopify store.
   Replace each one with the real product URL, e.g.
     'https://yourstore.com/products/daily-foundation'
   Buttons navigate there in the same tab after firing a tracking event.
   ========================================================================== */

var PRODUCTS = [
  {
    "slug": "daily-foundation",
    "name": "Daily Foundation",
    "sku": "EVERWELL-DAILYFOUNDAT",
    "category": "Men's Health",
    "shortBenefit": "A once-a-day base for a routine you will actually keep to.",
    "description": "[[PLACEHOLDER]] A once-a-day base for a routine you will actually keep to. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Foundation from Everwell. A once-a-day base for a routine you will actually keep to.",
    "price": 42,
    "compareAt": 52,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 612,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "One capsule, once a day",
      "Full ingredient list on the label",
      "No proprietary blends"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take as directed on the label as part of your daily routine. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/daily-foundation.svg",
    "gallery": [
      "images/products/daily-foundation.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Foundation]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-foundation"
  },
  {
    "slug": "nightly-reset",
    "name": "Nightly Reset",
    "sku": "EVERWELL-NIGHTLYRESET",
    "category": "Men's Health",
    "shortBenefit": "Formulated to support your evening routine.",
    "description": "[[PLACEHOLDER]] Formulated to support your evening routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Nightly Reset from Everwell. Formulated to support your evening routine.",
    "price": 38,
    "compareAt": 46,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 431,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Designed for the end of the day",
      "Clearly labelled contents",
      "Comes in a 30-day supply"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Use as directed on the label in the evening. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/nightly-reset.svg",
    "gallery": [
      "images/products/nightly-reset.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Nightly Reset]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/nightly-reset"
  },
  {
    "slug": "focus-support",
    "name": "Focus Support",
    "sku": "EVERWELL-FOCUSSUPPORT",
    "category": "Men's Health",
    "shortBenefit": "Made for the middle of a long day.",
    "description": "[[PLACEHOLDER]] Made for the middle of a long day. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Focus Support from Everwell. Made for the middle of a long day.",
    "price": 46,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.6,
    "reviewCount": 288,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Convenient daily format",
      "Transparent labelling",
      "Fits alongside the rest of the range"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take as directed on the label. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/focus-support.svg",
    "gallery": [
      "images/products/focus-support.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Focus Support]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/focus-support"
  },
  {
    "slug": "hair-thickening-serum",
    "name": "Thickening Serum",
    "sku": "EVERWELL-HAIRTHICKENI",
    "category": "Men's Health",
    "shortBenefit": "A daily topical step for your routine.",
    "description": "[[PLACEHOLDER]] A daily topical step for your routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Thickening Serum from Everwell. A daily topical step for your routine.",
    "price": 54,
    "compareAt": 68,
    "priceNote": "per 30-day supply",
    "rating": 4.5,
    "reviewCount": 356,
    "badge": "New",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Lightweight, non-greasy formula",
      "Applied once daily",
      "Unscented"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Apply to clean, dry skin as directed on the label. Patch test before first use.",
    "image": "images/products/hair-thickening-serum.svg",
    "gallery": [
      "images/products/hair-thickening-serum.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Thickening Serum]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/hair-thickening-serum"
  },
  {
    "slug": "post-training-recovery",
    "name": "Post-Training Recovery",
    "sku": "EVERWELL-POSTTRAINING",
    "category": "Men's Health",
    "shortBenefit": "Built into the part of the day you already plan around.",
    "description": "[[PLACEHOLDER]] Built into the part of the day you already plan around. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Post-Training Recovery from Everwell. Built into the part of the day you already plan around.",
    "price": 44,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 197,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Mixes into water or a shake",
      "Unflavoured option available",
      "30 servings per tub"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Mix one serving as directed on the label. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/post-training-recovery.svg",
    "gallery": [
      "images/products/post-training-recovery.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Post-Training Recovery]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/post-training-recovery"
  },
  {
    "slug": "gentle-gel-cleanser",
    "name": "Gentle Gel Cleanser",
    "sku": "EVERWELL-GENTLEGELCLE",
    "category": "Skincare",
    "shortBenefit": "A morning and evening first step that does not strip.",
    "description": "[[PLACEHOLDER]] A morning and evening first step that does not strip. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Gentle Gel Cleanser from Everwell. A morning and evening first step that does not strip.",
    "price": 28,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 894,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Fragrance-free",
      "Rinses clean",
      "150ml pump bottle"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Massage into damp skin and rinse. Use morning and evening, or as directed on the label.",
    "image": "images/products/gentle-gel-cleanser.svg",
    "gallery": [
      "images/products/gentle-gel-cleanser.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Gentle Gel Cleanser]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/gentle-gel-cleanser"
  },
  {
    "slug": "hydrating-serum",
    "name": "Hydrating Serum",
    "sku": "EVERWELL-HYDRATINGSER",
    "category": "Skincare",
    "shortBenefit": "The layer between cleansing and moisturising.",
    "description": "[[PLACEHOLDER]] The layer between cleansing and moisturising. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Hydrating Serum from Everwell. The layer between cleansing and moisturising.",
    "price": 46,
    "compareAt": 58,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 1120,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Lightweight, absorbs quickly",
      "Layers under moisturiser",
      "30ml dropper bottle"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Apply a few drops to clean skin before moisturiser, as directed on the label.",
    "image": "images/products/hydrating-serum.svg",
    "gallery": [
      "images/products/hydrating-serum.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Hydrating Serum]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/hydrating-serum"
  },
  {
    "slug": "daily-moisturiser",
    "name": "Daily Moisturiser",
    "sku": "EVERWELL-DAILYMOISTUR",
    "category": "Skincare",
    "shortBenefit": "A final step that sits well under makeup.",
    "description": "[[PLACEHOLDER]] A final step that sits well under makeup. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Moisturiser from Everwell. A final step that sits well under makeup.",
    "price": 38,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 742,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Non-greasy finish",
      "Fragrance-free",
      "50ml jar"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Apply to face and neck as the last step of your routine, as directed on the label.",
    "image": "images/products/daily-moisturiser.svg",
    "gallery": [
      "images/products/daily-moisturiser.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Moisturiser]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-moisturiser"
  },
  {
    "slug": "daily-spf-40",
    "name": "Daily SPF 40",
    "sku": "EVERWELL-DAILYSPF40",
    "category": "Skincare",
    "shortBenefit": "The step most routines skip.",
    "description": "[[PLACEHOLDER]] The step most routines skip. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily SPF 40 from Everwell. The step most routines skip.",
    "price": 34,
    "compareAt": 42,
    "priceNote": "per 30-day supply",
    "rating": 4.6,
    "reviewCount": 566,
    "badge": "New",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "No white cast",
      "Wears well under makeup",
      "50ml tube"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Apply generously as the final morning step and reapply as directed on the label.",
    "image": "images/products/daily-spf-40.svg",
    "gallery": [
      "images/products/daily-spf-40.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily SPF 40]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-spf-40"
  },
  {
    "slug": "overnight-recovery-balm",
    "name": "Overnight Recovery Balm",
    "sku": "EVERWELL-OVERNIGHTREC",
    "category": "Skincare",
    "shortBenefit": "A richer option for the end of the day.",
    "description": "[[PLACEHOLDER]] A richer option for the end of the day. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Overnight Recovery Balm from Everwell. A richer option for the end of the day.",
    "price": 52,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 318,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Richer evening texture",
      "A little goes a long way",
      "50ml jar"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Warm a small amount between fingertips and press into skin at night, as directed on the label.",
    "image": "images/products/overnight-recovery-balm.svg",
    "gallery": [
      "images/products/overnight-recovery-balm.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Overnight Recovery Balm]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/overnight-recovery-balm"
  },
  {
    "slug": "daily-balance-capsules",
    "name": "Daily Balance Capsules",
    "sku": "EVERWELL-DAILYBALANCE",
    "category": "Weight Management",
    "shortBenefit": "A once-daily capsule to sit alongside your routine.",
    "description": "[[PLACEHOLDER]] A once-daily capsule to sit alongside your routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Balance Capsules from Everwell. A once-daily capsule to sit alongside your routine.",
    "price": 44,
    "compareAt": 55,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 523,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "One capsule per day",
      "30-day supply",
      "Full ingredient list on the label"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take as directed on the label. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/daily-balance-capsules.svg",
    "gallery": [
      "images/products/daily-balance-capsules.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Balance Capsules]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-balance-capsules"
  },
  {
    "slug": "fibre-blend",
    "name": "Daily Fibre Blend",
    "sku": "EVERWELL-FIBREBLEND",
    "category": "Weight Management",
    "shortBenefit": "Mixes into water, coffee or a smoothie.",
    "description": "[[PLACEHOLDER]] Mixes into water, coffee or a smoothie. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Fibre Blend from Everwell. Mixes into water, coffee or a smoothie.",
    "price": 36,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.6,
    "reviewCount": 388,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Unflavoured",
      "30 servings",
      "Dissolves without clumping"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Mix one serving into a drink as directed on the label.",
    "image": "images/products/fibre-blend.svg",
    "gallery": [
      "images/products/fibre-blend.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Fibre Blend]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/fibre-blend"
  },
  {
    "slug": "protein-shake-vanilla",
    "name": "Protein Shake — Vanilla",
    "sku": "EVERWELL-PROTEINSHAKE",
    "category": "Weight Management",
    "shortBenefit": "A straightforward shake for busy mornings.",
    "description": "[[PLACEHOLDER]] A straightforward shake for busy mornings. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Protein Shake — Vanilla from Everwell. A straightforward shake for busy mornings.",
    "price": 48,
    "compareAt": 58,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 671,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "20 servings per pouch",
      "Mixes with water or milk",
      "Also available unflavoured"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Blend one scoop with liquid of your choice as directed on the label.",
    "image": "images/products/protein-shake-vanilla.svg",
    "gallery": [
      "images/products/protein-shake-vanilla.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Protein Shake — Vanilla]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/protein-shake-vanilla"
  },
  {
    "slug": "evening-support",
    "name": "Evening Support",
    "sku": "EVERWELL-EVENINGSUPPO",
    "category": "Weight Management",
    "shortBenefit": "Formulated for the end of the day.",
    "description": "[[PLACEHOLDER]] Formulated for the end of the day. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Evening Support from Everwell. Formulated for the end of the day.",
    "price": 34,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.5,
    "reviewCount": 244,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Designed for evening use",
      "30-day supply",
      "Clearly labelled"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take in the evening as directed on the label.",
    "image": "images/products/evening-support.svg",
    "gallery": [
      "images/products/evening-support.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Evening Support]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/evening-support"
  },
  {
    "slug": "hydration-sticks",
    "name": "Hydration Sticks",
    "sku": "EVERWELL-HYDRATIONSTI",
    "category": "Weight Management",
    "shortBenefit": "Single-serve sticks for a water bottle.",
    "description": "[[PLACEHOLDER]] Single-serve sticks for a water bottle. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Hydration Sticks from Everwell. Single-serve sticks for a water bottle.",
    "price": 26,
    "compareAt": 32,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 412,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "14 sticks per box",
      "Citrus flavour",
      "Fits in a pocket"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Add one stick to water as directed on the label.",
    "image": "images/products/hydration-sticks.svg",
    "gallery": [
      "images/products/hydration-sticks.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Hydration Sticks]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/hydration-sticks"
  },
  {
    "slug": "daily-multi",
    "name": "Daily Multi",
    "sku": "EVERWELL-DAILYMULTI",
    "category": "Daily Supplements",
    "shortBenefit": "One capsule covering the everyday basics.",
    "description": "[[PLACEHOLDER]] One capsule covering the everyday basics. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Multi from Everwell. One capsule covering the everyday basics.",
    "price": 32,
    "compareAt": 40,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 1340,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Every quantity printed on the label",
      "Third-party tested batches",
      "30-day supply"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take one capsule daily with food, as directed on the label.",
    "image": "images/products/daily-multi.svg",
    "gallery": [
      "images/products/daily-multi.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Multi]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-multi"
  },
  {
    "slug": "omega-3",
    "name": "Omega-3",
    "sku": "EVERWELL-OMEGA3",
    "category": "Daily Supplements",
    "shortBenefit": "A daily softgel with no aftertaste.",
    "description": "[[PLACEHOLDER]] A daily softgel with no aftertaste. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Omega-3 from Everwell. A daily softgel with no aftertaste.",
    "price": 34,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 806,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Third-party tested for purity",
      "60 softgels",
      "Full disclosure label"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take as directed on the label, ideally with a meal.",
    "image": "images/products/omega-3.svg",
    "gallery": [
      "images/products/omega-3.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Omega-3]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/omega-3"
  },
  {
    "slug": "magnesium-complex",
    "name": "Magnesium Complex",
    "sku": "EVERWELL-MAGNESIUMCOM",
    "category": "Daily Supplements",
    "shortBenefit": "Made to be the last thing in your routine.",
    "description": "[[PLACEHOLDER]] Made to be the last thing in your routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Magnesium Complex from Everwell. Made to be the last thing in your routine.",
    "price": 28,
    "compareAt": 34,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 923,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Designed for evening use",
      "60 capsules",
      "Third-party tested"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take in the evening as directed on the label.",
    "image": "images/products/magnesium-complex.svg",
    "gallery": [
      "images/products/magnesium-complex.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Magnesium Complex]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/magnesium-complex"
  },
  {
    "slug": "vitamin-d3-k2",
    "name": "Vitamin D3 + K2",
    "sku": "EVERWELL-VITAMIND3K2",
    "category": "Daily Supplements",
    "shortBenefit": "A small daily drop, easy to remember.",
    "description": "[[PLACEHOLDER]] A small daily drop, easy to remember. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Vitamin D3 + K2 from Everwell. A small daily drop, easy to remember.",
    "price": 26,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 655,
    "badge": "New",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Liquid drops, no capsule",
      "60-day supply",
      "Third-party tested"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take the number of drops stated on the label, with food.",
    "image": "images/products/vitamin-d3-k2.svg",
    "gallery": [
      "images/products/vitamin-d3-k2.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Vitamin D3 + K2]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/vitamin-d3-k2"
  },
  {
    "slug": "greens-powder",
    "name": "Greens Powder",
    "sku": "EVERWELL-GREENSPOWDER",
    "category": "Daily Supplements",
    "shortBenefit": "A daily scoop for water or a smoothie.",
    "description": "[[PLACEHOLDER]] A daily scoop for water or a smoothie. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Greens Powder from Everwell. A daily scoop for water or a smoothie.",
    "price": 42,
    "compareAt": 52,
    "priceNote": "per 30-day supply",
    "rating": 4.4,
    "reviewCount": 377,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "30 servings",
      "Mild flavour",
      "Every ingredient quantified"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Mix one scoop into liquid as directed on the label.",
    "image": "images/products/greens-powder.svg",
    "gallery": [
      "images/products/greens-powder.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Greens Powder]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/greens-powder"
  },
  {
    "slug": "night-capsules",
    "name": "Night Capsules",
    "sku": "EVERWELL-NIGHTCAPSULE",
    "category": "Sleep & Calm",
    "shortBenefit": "A once-nightly capsule for the end of your routine.",
    "description": "[[PLACEHOLDER]] A once-nightly capsule for the end of your routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Night Capsules from Everwell. A once-nightly capsule for the end of your routine.",
    "price": 38,
    "compareAt": 46,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 742,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "One capsule at night",
      "30-day supply",
      "Clear ingredient list"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take before bed as directed on the label. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/night-capsules.svg",
    "gallery": [
      "images/products/night-capsules.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Night Capsules]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/night-capsules"
  },
  {
    "slug": "calm-drops",
    "name": "Calm Drops",
    "sku": "EVERWELL-CALMDROPS",
    "category": "Sleep & Calm",
    "shortBenefit": "A liquid option for people who dislike capsules.",
    "description": "[[PLACEHOLDER]] A liquid option for people who dislike capsules. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Calm Drops from Everwell. A liquid option for people who dislike capsules.",
    "price": 42,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.6,
    "reviewCount": 511,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Measured dropper",
      "Unflavoured",
      "30ml bottle"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Use the dropper as directed on the label in the evening.",
    "image": "images/products/calm-drops.svg",
    "gallery": [
      "images/products/calm-drops.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Calm Drops]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/calm-drops"
  },
  {
    "slug": "wind-down-tea",
    "name": "Wind Down Tea",
    "sku": "EVERWELL-WINDDOWNTEA",
    "category": "Sleep & Calm",
    "shortBenefit": "A caffeine-free evening ritual.",
    "description": "[[PLACEHOLDER]] A caffeine-free evening ritual. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Wind Down Tea from Everwell. A caffeine-free evening ritual.",
    "price": 22,
    "compareAt": 28,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 894,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "30 bags per tin",
      "Caffeine-free",
      "Loose-leaf option available"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Steep as directed on the tin, ideally an hour before bed.",
    "image": "images/products/wind-down-tea.svg",
    "gallery": [
      "images/products/wind-down-tea.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Wind Down Tea]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/wind-down-tea"
  },
  {
    "slug": "magnesium-night",
    "name": "Magnesium Night",
    "sku": "EVERWELL-MAGNESIUMNIG",
    "category": "Sleep & Calm",
    "shortBenefit": "A simple, single-ingredient evening option.",
    "description": "[[PLACEHOLDER]] A simple, single-ingredient evening option. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Magnesium Night from Everwell. A simple, single-ingredient evening option.",
    "price": 30,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 623,
    "badge": "New",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "One ingredient, clearly stated",
      "60 capsules",
      "Third-party tested"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take in the evening as directed on the label.",
    "image": "images/products/magnesium-night.svg",
    "gallery": [
      "images/products/magnesium-night.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Magnesium Night]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/magnesium-night"
  },
  {
    "slug": "silk-sleep-mask",
    "name": "Silk Sleep Mask",
    "sku": "EVERWELL-SILKSLEEPMAS",
    "category": "Sleep & Calm",
    "shortBenefit": "A physical part of the routine, not a supplement.",
    "description": "[[PLACEHOLDER]] A physical part of the routine, not a supplement. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask from Everwell. A physical part of the routine, not a supplement.",
    "price": 34,
    "compareAt": 42,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 288,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Adjustable strap",
      "Machine washable bag included",
      "Blocks light fully"
    ],
    "ingredients": [
      "[[PLACEHOLDER: material composition]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Wear as part of your evening routine. Hand wash as directed on the care label.",
    "image": "images/products/silk-sleep-mask.svg",
    "gallery": [
      "images/products/silk-sleep-mask.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/silk-sleep-mask"
  },
  {
    "slug": "starter-bundle",
    "name": "The Starter Bundle",
    "sku": "EVERWELL-STARTERBUNDL",
    "category": "Bundles",
    "shortBenefit": "Three of the range together, at a lower price than buying separately.",
    "description": "[[PLACEHOLDER]] Three of the range together, at a lower price than buying separately. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Starter Bundle from Everwell. Three of the range together, at a lower price than buying separately.",
    "price": 96,
    "compareAt": 126,
    "priceNote": "one-off purchase",
    "rating": 4.9,
    "reviewCount": 143,
    "badge": "Save 24%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Daily Foundation, Focus Support and Evening Wind Down",
      "One delivery instead of three",
      "Cancel or change at any time"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the label directions for each product in the bundle.",
    "image": "images/products/starter-bundle.svg",
    "gallery": [
      "images/products/starter-bundle.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Starter Bundle]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/starter-bundle"
  },
  {
    "slug": "the-core-routine",
    "name": "The Core Routine",
    "sku": "EVERWELL-THECOREROUTI",
    "category": "Bundles",
    "shortBenefit": "Cleanser, serum, moisturiser and SPF, together.",
    "description": "[[PLACEHOLDER]] Cleanser, serum, moisturiser and SPF, together. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Core Routine from Everwell. Cleanser, serum, moisturiser and SPF, together.",
    "price": 104,
    "compareAt": 138,
    "priceNote": "one-off purchase",
    "rating": 4.9,
    "reviewCount": 402,
    "badge": "Save 25%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "All four core steps",
      "Cheaper than buying separately",
      "Arrives in one box"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Use in order: cleanse, serum, moisturise, then SPF in the morning.",
    "image": "images/products/the-core-routine.svg",
    "gallery": [
      "images/products/the-core-routine.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Core Routine]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/the-core-routine"
  },
  {
    "slug": "balance-starter-kit",
    "name": "Balance Starter Kit",
    "sku": "EVERWELL-BALANCESTART",
    "category": "Bundles",
    "shortBenefit": "Three products to cover the basics of a routine.",
    "description": "[[PLACEHOLDER]] Three products to cover the basics of a routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Balance Starter Kit from Everwell. Three products to cover the basics of a routine.",
    "price": 98,
    "compareAt": 128,
    "priceNote": "one-off purchase",
    "rating": 4.8,
    "reviewCount": 176,
    "badge": "Save 23%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Capsules, fibre blend and protein",
      "One delivery",
      "Pause or cancel anytime"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the label directions for each product in the kit.",
    "image": "images/products/balance-starter-kit.svg",
    "gallery": [
      "images/products/balance-starter-kit.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Balance Starter Kit]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/balance-starter-kit"
  },
  {
    "slug": "the-daily-three",
    "name": "The Daily Three",
    "sku": "EVERWELL-THEDAILYTHRE",
    "category": "Bundles",
    "shortBenefit": "Multi, Omega-3 and Magnesium in one subscription.",
    "description": "[[PLACEHOLDER]] Multi, Omega-3 and Magnesium in one subscription. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Daily Three from Everwell. Multi, Omega-3 and Magnesium in one subscription.",
    "price": 82,
    "compareAt": 106,
    "priceNote": "one-off purchase",
    "rating": 4.9,
    "reviewCount": 289,
    "badge": "Save 22%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Covers morning and evening",
      "15% off as a repeat order",
      "Pause or cancel anytime"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the label directions for each product in the bundle.",
    "image": "images/products/the-daily-three.svg",
    "gallery": [
      "images/products/the-daily-three.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Daily Three]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/the-daily-three"
  },
  {
    "slug": "evening-ritual-set",
    "name": "Evening Ritual Set",
    "sku": "EVERWELL-EVENINGRITUA",
    "category": "Bundles",
    "shortBenefit": "Capsules, tea and a sleep mask together.",
    "description": "[[PLACEHOLDER]] Capsules, tea and a sleep mask together. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Evening Ritual Set from Everwell. Capsules, tea and a sleep mask together.",
    "price": 84,
    "compareAt": 108,
    "priceNote": "one-off purchase",
    "rating": 4.8,
    "reviewCount": 164,
    "badge": "Save 22%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Covers the whole evening routine",
      "Arrives in one box",
      "Cheaper than buying separately"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the directions on each item in the set.",
    "image": "images/products/evening-ritual-set.svg",
    "gallery": [
      "images/products/evening-ritual-set.svg",
      "images/products/_angle-2.svg",
      "images/products/_angle-3.svg",
      "images/products/_angle-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Evening Ritual Set]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/evening-ritual-set"
  }
];

/* ========================================================================== */

var TESTIMONIALS = [
  {
    "name": "Daniel R.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] Ordering was simple and it turned up faster than I expected. The packaging was completely plain, which I appreciated."
  },
  {
    "name": "Priya S.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] I like being able to get my skincare and my supplements in one place instead of three different checkouts."
  },
  {
    "name": "Rachel K.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] What sold me was the absence of hype. It reads like a normal shop, not a pitch."
  },
  {
    "name": "Sam O.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] I asked for a batch certificate and they sent it the same day. That told me a lot."
  },
  {
    "name": "Adam F.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 4,
    "quote": "[[PLACEHOLDER]] Straightforward to order and easy to pause. Support replied the next morning."
  },
  {
    "name": "Elena M.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] Clear labels, quick delivery, and the packaging gives nothing away."
  }
];

var FAQS = [
  {
    "q": "How do I place an order?",
    "a": "[[PLACEHOLDER]] Choose the product you want and select Buy now. You will be taken to our secure store to complete checkout."
  },
  {
    "q": "How long does delivery take?",
    "a": "[[PLACEHOLDER: confirm real timings]] Orders are usually prepared for dispatch within a couple of business days. Delivery estimates are shown at checkout."
  },
  {
    "q": "Is the packaging discreet?",
    "a": "[[PLACEHOLDER]] Yes. Orders arrive in plain outer packaging with no product branding on the outside."
  },
  {
    "q": "Can I return something?",
    "a": "[[PLACEHOLDER: confirm real policy]] Unopened items can be returned within the window shown at checkout. Some health and personal care items cannot be returned once opened."
  },
  {
    "q": "Do you offer a subscription?",
    "a": "[[PLACEHOLDER]] Where a repeat option is available it is shown on the product page at checkout, and you can change or cancel it at any time."
  },
  {
    "q": "Should I speak to a healthcare professional first?",
    "a": "[[PLACEHOLDER]] If you are pregnant or breastfeeding, take prescription medicine, or have an existing medical condition, speak to a qualified healthcare professional before starting anything new. See our medical disclaimer."
  },
  {
    "q": "How do I contact support?",
    "a": "[[PLACEHOLDER]] Use the contact form, or email us directly. We aim to reply within one business day."
  },
  {
    "q": "Where do you ship?",
    "a": "[[PLACEHOLDER: list real destinations]] Shipping destinations and rates are shown at checkout."
  }
];
