/* ==========================================================================
   BRAND-CONFIG.JS — Lunelle Silk

   >>> THIS IS THE ONLY FILE YOU NEED TO EDIT. <<<

   Everything below drives the whole site: brand name, colours, products,
   prices, testimonials, FAQs, and the Shopify redirect links.

   TO GO LIVE, YOU MUST:
     1. Connect a payment provider — set BRAND.payment below.
     2. Replace every [[PLACEHOLDER: ...]] string.
     3. Replace the images in images/ and images/products/ with real photos.
     4. Add real tracking IDs below and set tracking.enabled to true.
     5. Remove the noindex tag from every .html file (search for "noindex").

   Find every remaining placeholder at once:
     grep -rn "PLACEHOLDER" .           (Mac/Linux)
     findstr /s /n "PLACEHOLDER" *.*    (Windows)
   ========================================================================== */

var BRAND = {
  /* The folder this site lives in. admin.html builds SKUs from it, so it has
     to match what generate.js used. */
  slug: "everwell",
  name: "Lunelle Silk",
  tagline: "A little silk. A lot to love.",
  announcement: "[[PLACEHOLDER]] Buy 3, get 1 free — ends Sunday",
  logo: 'images/logo.svg',

  /* ---- Colours. theme-init.js applies these before first paint. -------- */
  colors: {
  "background": "#ffffff",
  "surface": "#f7f8fb",
  "soft": "#f1f3f9",
  "text": "#2b3244",
  "heading": "#111a2e",
  "muted": "#6b7488",
  "border": "#e5e8f0",
  "borderStrong": "#c9cfdd",
  "accent": "#1b2a4e",
  "accentHover": "#111d3a",
  "accentTint": "#e9edf6",
  "onAccent": "#ffffff",
  "accentDeep": "#16233f",
  "accentDeeper": "#0c1630",
  "accentAlt": "#c0563c",
  "accentAltTint": "#fbeee9",
  "footerBg": "#111a2e",
  "footerText": "#c3c9d8",
  "star": "#dfa93f"
},

  style: {
  "radius": "14px",
  "radiusLarge": "22px",
  "buttonRadius": "999px",
  "cardStyle": "bordered",
  "logoWidth": "156px"
},

  currency: {
  "symbol": "$",
  "code": "USD",
  "decimals": 2
},

  /* Free over the threshold, otherwise the flat rate. Drives the basket
     totals and the free-delivery meter. */
  shipping: {
  "freeOver": 75,
  "flatRate": 6.95
},

  /* THE ONE PAYMENT INTEGRATION POINT.
       provider 'none' — nothing is charged; the order is confirmed and says so
       provider 'link' — send the basket to url (Stripe Payment Link, PayPal,
                         a Shopify cart permalink)
       provider 'form' — POST the order to endpoint, for a serverless function
                         that opens a real payment session
     Card details are never collected on this site. */
  payment: {
  "provider": "none",
  "url": "",
  "endpoint": ""
},

  /* Checkout: delivery options, discount codes and the reassurance panel. */
  shippingMethods: [
  {
    "id": "standard",
    "label": "Standard delivery",
    "eta": "5-8 business days",
    "price": 6.95,
    "freeOver": 75
  },
  {
    "id": "express",
    "label": "Express delivery",
    "eta": "2-3 business days",
    "price": 14.95
  },
  {
    "id": "priority",
    "label": "Priority overnight",
    "eta": "Next business day if ordered before 2pm",
    "price": 29.95
  }
],
  discounts: [
  {
    "code": "SILK10",
    "kind": "percent",
    "value": 10,
    "label": "10% off your order"
  },
  {
    "code": "WELCOME15",
    "kind": "amount",
    "value": 15,
    "label": "$15 off your order"
  },
  {
    "code": "FREESILK",
    "kind": "shipping",
    "value": 0,
    "label": "Free delivery"
  }
],
  checkoutTrust: [
  {
    "icon": "lock",
    "label": "Secure checkout"
  },
  {
    "icon": "truck",
    "label": "Fast shipping"
  },
  {
    "icon": "chat",
    "label": "Real people, real help"
  }
],
  guarantees: [
  {
    "title": "60-night sleep guarantee",
    "body": "Sleep on it for two months. If it is not for you, send it back for a full refund."
  },
  {
    "title": "Over 250,000 cases shipped",
    "body": "[[PLACEHOLDER: replace with your own figure once you have one.]]"
  }
],
  expressPay: [
  {
    "id": "shoppay",
    "label": "Shop Pay"
  },
  {
    "id": "paypal",
    "label": "PayPal"
  },
  {
    "id": "gpay",
    "label": "G Pay"
  }
],

  /* Every category has its own page. Generated by _tools/generate.js. */
  categoryPages: {
  "Pillowcases": "pillowcases.html",
  "Sleep Masks": "sleep-masks.html",
  "Scrunchies": "scrunchies.html",
  "Bundles": "bundles.html"
},
  /* Rendered into the footer, so removing a legal page cannot leave a dead link. */
  legalPages: [
  {
    "title": "Privacy Policy",
    "href": "privacy-policy.html"
  },
  {
    "title": "Terms of Service",
    "href": "terms-of-service.html"
  },
  {
    "title": "Shipping & Refund Policy",
    "href": "shipping-refund-policy.html"
  }
],
  categoryIndex: {
  "Pillowcases": 1,
  "Sleep Masks": 2,
  "Scrunchies": 3,
  "Bundles": 4
},
  categoryIcons: {
  "Pillowcases": "leaf",
  "Sleep Masks": "clock",
  "Scrunchies": "refresh",
  "Bundles": "box"
},

  contact: {
    email: "hello@lunelle-placeholder.com",
    phone: "+1 (555) 010-7788",
    hours: "Mon–Sat, 9am–7pm",
    address: "[[PLACEHOLDER: registered business address]]",
    legalEntity: "Lunelle Silk Ltd"
  },

  /* ---- Footer health disclaimer. Ad reviewers read this. --------------- */
  disclaimer: "[[PLACEHOLDER: health disclaimer]] The content on this site is for general information only and is not medical advice. Always speak to a qualified healthcare professional before starting, stopping or changing anything related to your health. Products are not intended to diagnose, treat, cure or prevent any disease.",

  copy: {
    buyCta: 'Buy now'
  },

  /* ---- Ad pixels. Nothing loads or fires until enabled is true. -------- */
  tracking: {
    enabled: false,
    ga4MeasurementId: '',            // 'G-XXXXXXXXXX'
    googleAdsConversionId: '',       // 'AW-XXXXXXXXX'
    googleAdsConversionLabel: '',    // the label from the conversion action
    metaPixelId: ''                  // numeric ID only
  },

  seo: {
    /* Leave false until a real review app supplies ratings. Invented ratings
       in structured data get Merchant Center accounts suspended. */
    emitAggregateRating: false
  },

  heroProof: [
  "Free delivery over $75",
  "60-night trial",
  "Gift-boxed"
],
  marquee: [
  "Free delivery over $75",
  "60-night trial",
  "22-momme mulberry silk",
  "Silk on both sides",
  "Gift-boxed as standard",
  "Machine washable",
  "Buy 3, get 1 free"
],
  goals: [],
  heroProducts: [
  "silk-pillowcase-champagne",
  "silk-pillowcase-blush",
  "silk-pillowcase-midnight"
],
  awards: [
  {
    "value": "230,000+",
    "label": "[[PLACEHOLDER]] 5-star reviews"
  },
  {
    "value": "2023–25",
    "label": "[[PLACEHOLDER]] Most gifted, three years"
  },
  {
    "value": "22",
    "label": "Momme mulberry silk"
  },
  {
    "value": "60",
    "label": "Night trial"
  }
],
  press: [
  "[[PLACEHOLDER]] VOGUE",
  "FORBES",
  "ELLE",
  "GQ",
  "HARPER&rsquo;S",
  "ALLURE"
],
  newArrivals: [
  "silk-pillowcase-sage",
  "silk-pillowcase-lavender",
  "silk-pillowcase-gold"
],
  qualityPicks: [
  "silk-pillowcase-champagne",
  "the-sleep-set",
  "silk-sleep-mask-champagne"
],
  spotlightSlug: "silk-pillowcase-champagne",
  promo: {
  "tag": "This week",
  "heading": "Buy 3, get 1 free",
  "text": "Mix any colours and any sizes. The cheapest of the four comes off at checkout.",
  "code": "SILK4",
  "cta": "Shop the offer"
},
  valueProps: [
  {
    "icon": "truck",
    "text": "Free delivery over $75"
  },
  {
    "icon": "box",
    "text": "Gift-boxed as standard"
  },
  {
    "icon": "refresh",
    "text": "60-night trial"
  },
  {
    "icon": "chat",
    "text": "Support in 24h"
  }
],
  howItWorks: [
  {
    "title": "Pick your colour",
    "text": "Every colour, in three sizes. Swatches on each product page."
  },
  {
    "title": "We box it up",
    "text": "Gift box and ribbon as standard, note optional at checkout."
  },
  {
    "title": "Sleep on it",
    "text": "Sixty nights to decide. Send it back if it is not for you."
  }
],
  trustBadges: [
  {
    "icon": "leaf",
    "title": "22-momme mulberry silk",
    "text": "Silk on both sides, not one."
  },
  {
    "icon": "refresh",
    "title": "60-night trial",
    "text": "Sleep on it. Send it back if it is not for you."
  },
  {
    "icon": "box",
    "title": "Gift-boxed as standard",
    "text": "Box and ribbon on every order."
  },
  {
    "icon": "truck",
    "title": "Free delivery over $75",
    "text": "Tracked, and quicker than the estimate."
  }
],
  productReassurance: [
  {
    "icon": "truck",
    "text": "Free delivery over $75"
  },
  {
    "icon": "box",
    "text": "Arrives gift-boxed"
  },
  {
    "icon": "refresh",
    "text": "60 nights to change your mind"
  },
  {
    "icon": "lock",
    "text": "Secure checkout"
  }
],
  values: [
  {
    "icon": "leaf",
    "title": "One thing, done properly",
    "text": "A single pillowcase done properly, rather than a catalogue."
  },
  {
    "icon": "shield",
    "title": "Silk on both faces",
    "text": "Not silk on one side and cotton on the other, which is the usual trick."
  },
  {
    "icon": "refresh",
    "title": "Made to be washed",
    "text": "Cool delicate cycle at home. No dry cleaning, no hand washing."
  },
  {
    "icon": "chat",
    "title": "Support that answers",
    "text": "Real people, replying within one business day."
  }
],
  stats: [
  {
    "value": "230000",
    "label": "[[PLACEHOLDER]] 5-star reviews",
    "display": "230k+"
  },
  {
    "value": "4.9",
    "label": "Average rating"
  },
  {
    "value": "22",
    "label": "Momme mulberry silk"
  },
  {
    "value": "60",
    "label": "Night trial"
  }
],
  aboutPoints: [
  "Every piece is 22-momme mulberry silk",
  "Hidden zip on every pillowcase",
  "OEKO-TEX certified dyes",
  "Sixty nights to change your mind"
]
};

/* ==========================================================================
   PRODUCTS
   The basket and checkout live on this site. Adding a product here puts it in
   the shop, the filters, its category page and its own product page, and it
   becomes buyable — no per-product link to maintain.
   ========================================================================== */

var PRODUCTS = [
  {
    "slug": "silk-pillowcase-champagne",
    "name": "Silk Pillowcase — Champagne",
    "sku": "EVERWELL-SILKPILLOWCASECHAMPAGNE",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Champagne from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 4820,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-champagne.svg",
    "gallery": [
      "images/products/silk-pillowcase-champagne.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Champagne]]",
    "swatch": "#e8dcc6",
    "colour": "Champagne",
    "tint": "#fcfaf7",
    "deep": "#686359"
  },
  {
    "slug": "silk-pillowcase-ivory",
    "name": "Silk Pillowcase — Ivory",
    "sku": "EVERWELL-SILKPILLOWCASEIVORY",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Ivory from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 3140,
    "badge": null,
    "featured": true,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-ivory.svg",
    "gallery": [
      "images/products/silk-pillowcase-ivory.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Ivory]]",
    "swatch": "#f2ece1",
    "colour": "Ivory",
    "tint": "#fdfcfb",
    "deep": "#6d6a65"
  },
  {
    "slug": "silk-pillowcase-blush",
    "name": "Silk Pillowcase — Blush",
    "sku": "EVERWELL-SILKPILLOWCASEBLUSH",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Blush from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 2760,
    "badge": null,
    "featured": true,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-blush.svg",
    "gallery": [
      "images/products/silk-pillowcase-blush.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Blush]]",
    "swatch": "#edd3d1",
    "colour": "Blush",
    "tint": "#fcf9f9",
    "deep": "#6b5f5e"
  },
  {
    "slug": "silk-pillowcase-midnight",
    "name": "Silk Pillowcase — Midnight",
    "sku": "EVERWELL-SILKPILLOWCASEMIDNIGHT",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Midnight from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 2210,
    "badge": null,
    "featured": true,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-midnight.svg",
    "gallery": [
      "images/products/silk-pillowcase-midnight.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Midnight]]",
    "swatch": "#2a3350",
    "colour": "Midnight",
    "tint": "#e1e2e7",
    "deep": "#131724"
  },
  {
    "slug": "silk-pillowcase-sage",
    "name": "Silk Pillowcase — Sage",
    "sku": "EVERWELL-SILKPILLOWCASESAGE",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Sage from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 1180,
    "badge": "New",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-sage.svg",
    "gallery": [
      "images/products/silk-pillowcase-sage.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Sage]]",
    "swatch": "#cdd8c8",
    "colour": "Sage",
    "tint": "#f8faf7",
    "deep": "#5c615a"
  },
  {
    "slug": "silk-pillowcase-lavender",
    "name": "Silk Pillowcase — Lavender",
    "sku": "EVERWELL-SILKPILLOWCASELAVENDER",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Lavender from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 960,
    "badge": "New",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-lavender.svg",
    "gallery": [
      "images/products/silk-pillowcase-lavender.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Lavender]]",
    "swatch": "#d8d2e6",
    "colour": "Lavender",
    "tint": "#faf9fc",
    "deep": "#615e67"
  },
  {
    "slug": "silk-pillowcase-pearl",
    "name": "Silk Pillowcase — Pearl",
    "sku": "EVERWELL-SILKPILLOWCASEPEARL",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Pearl from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": null,
    "rating": 4.7,
    "reviewCount": 1540,
    "badge": null,
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-pearl.svg",
    "gallery": [
      "images/products/silk-pillowcase-pearl.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Pearl]]",
    "swatch": "#e4e6ea",
    "colour": "Pearl",
    "tint": "#fbfcfc",
    "deep": "#676769"
  },
  {
    "slug": "silk-pillowcase-gold",
    "name": "Silk Pillowcase — Gold",
    "sku": "EVERWELL-SILKPILLOWCASEGOLD",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Gold from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 99,
    "compareAt": 124,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 870,
    "badge": "New",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-gold.svg",
    "gallery": [
      "images/products/silk-pillowcase-gold.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Gold]]",
    "swatch": "#dfc68c",
    "colour": "Gold",
    "tint": "#fbf7ef",
    "deep": "#64593f"
  },
  {
    "slug": "silk-pillowcase-rose",
    "name": "Silk Pillowcase — Rose",
    "sku": "EVERWELL-SILKPILLOWCASEROSE",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Rose from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 1240,
    "badge": null,
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-rose.svg",
    "gallery": [
      "images/products/silk-pillowcase-rose.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Rose]]",
    "swatch": "#e2b8b8",
    "colour": "Rose",
    "tint": "#fbf5f5",
    "deep": "#665353"
  },
  {
    "slug": "silk-pillowcase-charcoal",
    "name": "Silk Pillowcase — Charcoal",
    "sku": "EVERWELL-SILKPILLOWCASECHARCOAL",
    "category": "Pillowcases",
    "shortBenefit": "22-momme mulberry silk, both sides.",
    "description": "[[PLACEHOLDER]] 22-momme mulberry silk, both sides. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Pillowcase — Charcoal from Lunelle Silk. 22-momme mulberry silk, both sides.",
    "price": 89,
    "compareAt": 109,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 1680,
    "badge": null,
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "100% mulberry silk, 22 momme",
      "Hidden zip, silk on both sides",
      "Machine washable on a delicate cycle"
    ],
    "ingredients": [
      "[[PLACEHOLDER]] 100% mulberry silk",
      "[[PLACEHOLDER]] OEKO-TEX certified dye"
    ],
    "howItWorks": "Slip it over your usual pillow and sleep on it. Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/silk-pillowcase-charcoal.svg",
    "gallery": [
      "images/products/silk-pillowcase-charcoal.svg",
      "images/products/_angle-pillowcases-2.svg",
      "images/products/_angle-pillowcases-3.svg",
      "images/products/_angle-pillowcases-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Pillowcase — Charcoal]]",
    "swatch": "#4a4e58",
    "colour": "Charcoal",
    "tint": "#e6e6e8",
    "deep": "#212328"
  },
  {
    "slug": "silk-sleep-mask-champagne",
    "name": "Silk Sleep Mask — Champagne",
    "sku": "EVERWELL-SILKSLEEPMASKCHAMPAGNE",
    "category": "Sleep Masks",
    "shortBenefit": "Blocks the light, adjustable strap.",
    "description": "[[PLACEHOLDER]] Blocks the light, adjustable strap. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Champagne from Lunelle Silk. Blocks the light, adjustable strap.",
    "price": 39,
    "compareAt": 49,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 1420,
    "badge": "Popular",
    "featured": true,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "22-momme mulberry silk",
      "Adjustable, no-snag strap",
      "Travel pouch included"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Adjust the strap and wear it over the eyes. Hand wash cool.",
    "image": "images/products/silk-sleep-mask-champagne.svg",
    "gallery": [
      "images/products/silk-sleep-mask-champagne.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Champagne]]",
    "swatch": "#e8dcc6",
    "colour": "Champagne",
    "tint": "#fcfaf7",
    "deep": "#686359"
  },
  {
    "slug": "silk-sleep-mask-midnight",
    "name": "Silk Sleep Mask — Midnight",
    "sku": "EVERWELL-SILKSLEEPMASKMIDNIGHT",
    "category": "Sleep Masks",
    "shortBenefit": "Blocks the light, adjustable strap.",
    "description": "[[PLACEHOLDER]] Blocks the light, adjustable strap. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Midnight from Lunelle Silk. Blocks the light, adjustable strap.",
    "price": 39,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 980,
    "badge": null,
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "22-momme mulberry silk",
      "Adjustable, no-snag strap",
      "Travel pouch included"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Adjust the strap and wear it over the eyes. Hand wash cool.",
    "image": "images/products/silk-sleep-mask-midnight.svg",
    "gallery": [
      "images/products/silk-sleep-mask-midnight.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Midnight]]",
    "swatch": "#2a3350",
    "colour": "Midnight",
    "tint": "#e1e2e7",
    "deep": "#131724"
  },
  {
    "slug": "silk-sleep-mask-ivory",
    "name": "Silk Sleep Mask — Ivory",
    "sku": "EVERWELL-SILKSLEEPMASKIVORY",
    "category": "Sleep Masks",
    "shortBenefit": "Pure silk contour mask for restful sleep.",
    "description": "[[PLACEHOLDER]] Pure silk contour mask for restful sleep. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Ivory from Lunelle Silk. Pure silk contour mask for restful sleep.",
    "price": 39,
    "compareAt": 49,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 840,
    "badge": null,
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "22-momme mulberry silk",
      "Light-blocking design",
      "Travel pouch included"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Adjust strap for a snug fit. Hand wash cool.",
    "image": "images/products/silk-sleep-mask-ivory.svg",
    "gallery": [
      "images/products/silk-sleep-mask-ivory.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Ivory]]",
    "swatch": "#f2ece1",
    "colour": "Ivory",
    "tint": "#fdfcfb",
    "deep": "#6d6a65"
  },
  {
    "slug": "silk-sleep-mask-blush",
    "name": "Silk Sleep Mask — Blush",
    "sku": "EVERWELL-SILKSLEEPMASKBLUSH",
    "category": "Sleep Masks",
    "shortBenefit": "Gentle on eyes and lashes.",
    "description": "[[PLACEHOLDER]] Gentle on eyes and lashes. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Blush from Lunelle Silk. Gentle on eyes and lashes.",
    "price": 39,
    "compareAt": 49,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 920,
    "badge": "Best Seller",
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "22-momme mulberry silk",
      "Smooth plush inner layer",
      "Gentle strap"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Place over eyes before sleep.",
    "image": "images/products/silk-sleep-mask-blush.svg",
    "gallery": [
      "images/products/silk-sleep-mask-blush.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Blush]]",
    "swatch": "#edd3d1",
    "colour": "Blush",
    "tint": "#fcf9f9",
    "deep": "#6b5f5e"
  },
  {
    "slug": "silk-sleep-mask-rose",
    "name": "Silk Sleep Mask — Rose",
    "sku": "EVERWELL-SILKSLEEPMASKROSE",
    "category": "Sleep Masks",
    "shortBenefit": "Deep light blocking for travel or home.",
    "description": "[[PLACEHOLDER]] Deep light blocking for travel or home. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Rose from Lunelle Silk. Deep light blocking for travel or home.",
    "price": 39,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 650,
    "badge": null,
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "Ultra-soft silk padding",
      "Breathable natural fabric",
      "No-tangle elastic"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Adjust strap and rest peacefully.",
    "image": "images/products/silk-sleep-mask-rose.svg",
    "gallery": [
      "images/products/silk-sleep-mask-rose.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Rose]]",
    "swatch": "#e2b8b8",
    "colour": "Rose",
    "tint": "#fbf5f5",
    "deep": "#665353"
  },
  {
    "slug": "silk-sleep-mask-sage",
    "name": "Silk Sleep Mask — Sage",
    "sku": "EVERWELL-SILKSLEEPMASKSAGE",
    "category": "Sleep Masks",
    "shortBenefit": "Calming sage tone in 22-momme silk.",
    "description": "[[PLACEHOLDER]] Calming sage tone in 22-momme silk. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Sage from Lunelle Silk. Calming sage tone in 22-momme silk.",
    "price": 39,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.7,
    "reviewCount": 510,
    "badge": "New",
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "Soothing natural silk",
      "Protects delicate eye skin",
      "Includes storage pouch"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Adjust strap to your comfort level.",
    "image": "images/products/silk-sleep-mask-sage.svg",
    "gallery": [
      "images/products/silk-sleep-mask-sage.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Sage]]",
    "swatch": "#cdd8c8",
    "colour": "Sage",
    "tint": "#f8faf7",
    "deep": "#5c615a"
  },
  {
    "slug": "silk-sleep-mask-lavender",
    "name": "Silk Sleep Mask — Lavender",
    "sku": "EVERWELL-SILKSLEEPMASKLAVENDER",
    "category": "Sleep Masks",
    "shortBenefit": "Soft lavender silk mask.",
    "description": "[[PLACEHOLDER]] Soft lavender silk mask. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Lavender from Lunelle Silk. Soft lavender silk mask.",
    "price": 39,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 430,
    "badge": "New",
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "Hypoallergenic mulberry silk",
      "Completely blackout",
      "Elastic band covered in silk"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Wear comfortably overnight.",
    "image": "images/products/silk-sleep-mask-lavender.svg",
    "gallery": [
      "images/products/silk-sleep-mask-lavender.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Lavender]]",
    "swatch": "#d8d2e6",
    "colour": "Lavender",
    "tint": "#faf9fc",
    "deep": "#615e67"
  },
  {
    "slug": "silk-sleep-mask-pearl",
    "name": "Silk Sleep Mask — Pearl",
    "sku": "EVERWELL-SILKSLEEPMASKPEARL",
    "category": "Sleep Masks",
    "shortBenefit": "Luminous pearl silk mask.",
    "description": "[[PLACEHOLDER]] Luminous pearl silk mask. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Pearl from Lunelle Silk. Luminous pearl silk mask.",
    "price": 39,
    "compareAt": 49,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 760,
    "badge": null,
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "22-momme pure silk",
      "Smooth texture prevents creasing",
      "Lightweight design"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Hand wash cool and dry flat.",
    "image": "images/products/silk-sleep-mask-pearl.svg",
    "gallery": [
      "images/products/silk-sleep-mask-pearl.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Pearl]]",
    "swatch": "#e4e6ea",
    "colour": "Pearl",
    "tint": "#fbfcfc",
    "deep": "#676769"
  },
  {
    "slug": "silk-sleep-mask-gold",
    "name": "Silk Sleep Mask — Gold",
    "sku": "EVERWELL-SILKSLEEPMASKGOLD",
    "category": "Sleep Masks",
    "shortBenefit": "Luxurious gold silk with blackout padding.",
    "description": "[[PLACEHOLDER]] Luxurious gold silk with blackout padding. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Gold from Lunelle Silk. Luxurious gold silk with blackout padding.",
    "price": 45,
    "compareAt": 55,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 380,
    "badge": "Limited Edition",
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "Premium gold mulberry silk",
      "Padded for ultimate light block",
      "Gift box included"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Fit strap around head gently.",
    "image": "images/products/silk-sleep-mask-gold.svg",
    "gallery": [
      "images/products/silk-sleep-mask-gold.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Gold]]",
    "swatch": "#dfc68c",
    "colour": "Gold",
    "tint": "#fbf7ef",
    "deep": "#64593f"
  },
  {
    "slug": "silk-sleep-mask-charcoal",
    "name": "Silk Sleep Mask — Charcoal",
    "sku": "EVERWELL-SILKSLEEPMASKCHARCOAL",
    "category": "Sleep Masks",
    "shortBenefit": "Deep charcoal shade for total blackout.",
    "description": "[[PLACEHOLDER]] Deep charcoal shade for total blackout. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Sleep Mask — Charcoal from Lunelle Silk. Deep charcoal shade for total blackout.",
    "price": 39,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 590,
    "badge": null,
    "featured": false,
    "optionLabel": "Fit",
    "options": [
      "One size"
    ],
    "benefits": [
      "Dark weave for 100% blackout",
      "Cooling silk feel",
      "Strap covered in soft silk"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Adjust and wear for night or travel.",
    "image": "images/products/silk-sleep-mask-charcoal.svg",
    "gallery": [
      "images/products/silk-sleep-mask-charcoal.svg",
      "images/products/_angle-sleep-masks-2.svg",
      "images/products/_angle-sleep-masks-3.svg",
      "images/products/_angle-sleep-masks-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Sleep Mask — Charcoal]]",
    "swatch": "#4a4e58",
    "colour": "Charcoal",
    "tint": "#e6e6e8",
    "deep": "#212328"
  },
  {
    "slug": "silk-scrunchies-neutrals",
    "name": "Silk Scrunchies — Neutrals",
    "sku": "EVERWELL-SILKSCRUNCHIESNEUTRALS",
    "category": "Scrunchies",
    "shortBenefit": "Set of three, no-crease.",
    "description": "[[PLACEHOLDER]] Set of three, no-crease. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Neutrals from Lunelle Silk. Set of three, no-crease.",
    "price": 29,
    "compareAt": 36,
    "priceNote": null,
    "rating": 4.7,
    "reviewCount": 2310,
    "badge": null,
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Three scrunchies per set",
      "Soft elastic, holds without pulling",
      "22-momme mulberry silk"
    ],
    "ingredients": [
      "100% mulberry silk",
      "Covered elastic"
    ],
    "howItWorks": "Wear as you would any hair tie. Hand wash cool.",
    "image": "images/products/silk-scrunchies-neutrals.svg",
    "gallery": [
      "images/products/silk-scrunchies-neutrals.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Neutrals]]",
    "swatch": "#f2ece1",
    "colour": "Neutrals",
    "tint": "#fdfcfb",
    "deep": "#6d6a65"
  },
  {
    "slug": "silk-scrunchies-jewels",
    "name": "Silk Scrunchies — Jewels",
    "sku": "EVERWELL-SILKSCRUNCHIESJEWELS",
    "category": "Scrunchies",
    "shortBenefit": "Set of three, no-crease.",
    "description": "[[PLACEHOLDER]] Set of three, no-crease. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Jewels from Lunelle Silk. Set of three, no-crease.",
    "price": 29,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.7,
    "reviewCount": 1160,
    "badge": "New",
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Three scrunchies per set",
      "Soft elastic, holds without pulling",
      "22-momme mulberry silk"
    ],
    "ingredients": [
      "100% mulberry silk",
      "Covered elastic"
    ],
    "howItWorks": "Wear as you would any hair tie. Hand wash cool.",
    "image": "images/products/silk-scrunchies-jewels.svg",
    "gallery": [
      "images/products/silk-scrunchies-jewels.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Jewels]]",
    "swatch": "#d8d2e6",
    "colour": "Jewels",
    "tint": "#faf9fc",
    "deep": "#615e67"
  },
  {
    "slug": "silk-scrunchies-champagne-trio",
    "name": "Silk Scrunchies — Champagne Trio",
    "sku": "EVERWELL-SILKSCRUNCHIESCHAMPAGNETRIO",
    "category": "Scrunchies",
    "shortBenefit": "Three Champagne silk scrunchies.",
    "description": "[[PLACEHOLDER]] Three Champagne silk scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Champagne Trio from Lunelle Silk. Three Champagne silk scrunchies.",
    "price": 29,
    "compareAt": 36,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 1840,
    "badge": "Best Seller",
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Gentle on hair shafts",
      "Reduces breakage & dents",
      "22-momme mulberry silk"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Wrap around hair 2-3 times.",
    "image": "images/products/silk-scrunchies-champagne-trio.svg",
    "gallery": [
      "images/products/silk-scrunchies-champagne-trio.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Champagne Trio]]",
    "swatch": "#e8dcc6",
    "colour": "Champagne",
    "tint": "#fcfaf7",
    "deep": "#686359"
  },
  {
    "slug": "silk-scrunchies-midnight-trio",
    "name": "Silk Scrunchies — Midnight Trio",
    "sku": "EVERWELL-SILKSCRUNCHIESMIDNIGHTTRIO",
    "category": "Scrunchies",
    "shortBenefit": "Three Midnight navy silk scrunchies.",
    "description": "[[PLACEHOLDER]] Three Midnight navy silk scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Midnight Trio from Lunelle Silk. Three Midnight navy silk scrunchies.",
    "price": 29,
    "compareAt": 36,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 1290,
    "badge": null,
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Sleek dark silk finish",
      "Prevents frizz and split ends",
      "Durable inner band"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Ideal for sleep buns or daytime styles.",
    "image": "images/products/silk-scrunchies-midnight-trio.svg",
    "gallery": [
      "images/products/silk-scrunchies-midnight-trio.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Midnight Trio]]",
    "swatch": "#2a3350",
    "colour": "Midnight",
    "tint": "#e1e2e7",
    "deep": "#131724"
  },
  {
    "slug": "silk-scrunchies-blush-trio",
    "name": "Silk Scrunchies — Blush Trio",
    "sku": "EVERWELL-SILKSCRUNCHIESBLUSHTRIO",
    "category": "Scrunchies",
    "shortBenefit": "Three romantic Blush pink scrunchies.",
    "description": "[[PLACEHOLDER]] Three romantic Blush pink scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Blush Trio from Lunelle Silk. Three romantic Blush pink scrunchies.",
    "price": 29,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 940,
    "badge": null,
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Soft blush tone",
      "Glides off hair smoothly",
      "100% pure silk outer"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Gentle hold for all hair types.",
    "image": "images/products/silk-scrunchies-blush-trio.svg",
    "gallery": [
      "images/products/silk-scrunchies-blush-trio.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Blush Trio]]",
    "swatch": "#edd3d1",
    "colour": "Blush",
    "tint": "#fcf9f9",
    "deep": "#6b5f5e"
  },
  {
    "slug": "silk-scrunchies-rose-trio",
    "name": "Silk Scrunchies — Rose Trio",
    "sku": "EVERWELL-SILKSCRUNCHIESROSETRIO",
    "category": "Scrunchies",
    "shortBenefit": "Three elegant Rose silk scrunchies.",
    "description": "[[PLACEHOLDER]] Three elegant Rose silk scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Rose Trio from Lunelle Silk. Three elegant Rose silk scrunchies.",
    "price": 29,
    "compareAt": 36,
    "priceNote": null,
    "rating": 4.7,
    "reviewCount": 720,
    "badge": null,
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Deep rose hue",
      "Snag-free hold",
      "Machine washable delicate"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Use daily to prevent hair damage.",
    "image": "images/products/silk-scrunchies-rose-trio.svg",
    "gallery": [
      "images/products/silk-scrunchies-rose-trio.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Rose Trio]]",
    "swatch": "#e2b8b8",
    "colour": "Rose",
    "tint": "#fbf5f5",
    "deep": "#665353"
  },
  {
    "slug": "silk-scrunchies-sage-trio",
    "name": "Silk Scrunchies — Sage Trio",
    "sku": "EVERWELL-SILKSCRUNCHIESSAGETRIO",
    "category": "Scrunchies",
    "shortBenefit": "Three soothing Sage silk scrunchies.",
    "description": "[[PLACEHOLDER]] Three soothing Sage silk scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Sage Trio from Lunelle Silk. Three soothing Sage silk scrunchies.",
    "price": 29,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 580,
    "badge": "New",
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Modern pastel green",
      "Holds tight without headaches",
      "22-momme grade silk"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Wrap gently around ponytails or buns.",
    "image": "images/products/silk-scrunchies-sage-trio.svg",
    "gallery": [
      "images/products/silk-scrunchies-sage-trio.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Sage Trio]]",
    "swatch": "#cdd8c8",
    "colour": "Sage",
    "tint": "#f8faf7",
    "deep": "#5c615a"
  },
  {
    "slug": "silk-scrunchies-lavender-trio",
    "name": "Silk Scrunchies — Lavender Trio",
    "sku": "EVERWELL-SILKSCRUNCHIESLAVENDERTRIO",
    "category": "Scrunchies",
    "shortBenefit": "Three soft Lavender silk hair ties.",
    "description": "[[PLACEHOLDER]] Three soft Lavender silk hair ties. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Lavender Trio from Lunelle Silk. Three soft Lavender silk hair ties.",
    "price": 29,
    "compareAt": null,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 490,
    "badge": "New",
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Dreamy lavender tint",
      "Non-damaging elastic",
      "Ultra smooth finish"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Perfect for overnight hair protection.",
    "image": "images/products/silk-scrunchies-lavender-trio.svg",
    "gallery": [
      "images/products/silk-scrunchies-lavender-trio.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Lavender Trio]]",
    "swatch": "#d8d2e6",
    "colour": "Lavender",
    "tint": "#faf9fc",
    "deep": "#615e67"
  },
  {
    "slug": "silk-scrunchies-pearl-gold",
    "name": "Silk Scrunchies — Pearl & Gold Set",
    "sku": "EVERWELL-SILKSCRUNCHIESPEARLGOLD",
    "category": "Scrunchies",
    "shortBenefit": "Premium 4-pack of Pearl and Gold scrunchies.",
    "description": "[[PLACEHOLDER]] Premium 4-pack of Pearl and Gold scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Pearl & Gold Set from Lunelle Silk. Premium 4-pack of Pearl and Gold scrunchies.",
    "price": 34,
    "compareAt": 42,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 630,
    "badge": "Special Value",
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 4"
    ],
    "benefits": [
      "Includes 2 Pearl & 2 Gold scrunchies",
      "High shine finish",
      "Great for gifting"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Mix and match for styles.",
    "image": "images/products/silk-scrunchies-pearl-gold.svg",
    "gallery": [
      "images/products/silk-scrunchies-pearl-gold.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Pearl & Gold Set]]",
    "swatch": "#dfc68c",
    "colour": "Gold",
    "tint": "#fbf7ef",
    "deep": "#64593f"
  },
  {
    "slug": "silk-scrunchies-charcoal-trio",
    "name": "Silk Scrunchies — Charcoal Trio",
    "sku": "EVERWELL-SILKSCRUNCHIESCHARCOALTRIO",
    "category": "Scrunchies",
    "shortBenefit": "Three versatile Charcoal grey scrunchies.",
    "description": "[[PLACEHOLDER]] Three versatile Charcoal grey scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Silk Scrunchies — Charcoal Trio from Lunelle Silk. Three versatile Charcoal grey scrunchies.",
    "price": 29,
    "compareAt": 36,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 810,
    "badge": null,
    "featured": false,
    "optionLabel": "Set",
    "options": [
      "Set of 3"
    ],
    "benefits": [
      "Classic neutral charcoal",
      "Strong hold for thick hair",
      "Smooth silk exterior"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Hand wash cool.",
    "image": "images/products/silk-scrunchies-charcoal-trio.svg",
    "gallery": [
      "images/products/silk-scrunchies-charcoal-trio.svg",
      "images/products/_angle-scrunchies-2.svg",
      "images/products/_angle-scrunchies-3.svg",
      "images/products/_angle-scrunchies-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Silk Scrunchies — Charcoal Trio]]",
    "swatch": "#4a4e58",
    "colour": "Charcoal",
    "tint": "#e6e6e8",
    "deep": "#212328"
  },
  {
    "slug": "the-sleep-set",
    "name": "The Sleep Set",
    "sku": "EVERWELL-THESLEEPSET",
    "category": "Bundles",
    "shortBenefit": "Pillowcase, sleep mask and scrunchies.",
    "description": "[[PLACEHOLDER]] Pillowcase, sleep mask and scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Sleep Set from Lunelle Silk. Pillowcase, sleep mask and scrunchies.",
    "price": 139,
    "compareAt": 179,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 1640,
    "badge": "Save 22%",
    "featured": true,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "One pillowcase, one mask, one scrunchie set",
      "Arrives gift-boxed",
      "Cheaper than buying separately"
    ],
    "ingredients": [
      "100% mulberry silk throughout"
    ],
    "howItWorks": "Follow the care label on each piece. Wash cool, hang to dry.",
    "image": "images/products/the-sleep-set.svg",
    "gallery": [
      "images/products/the-sleep-set.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Sleep Set]]",
    "swatch": "#e2b8b8",
    "colour": "Blush",
    "tint": "#fbf5f5",
    "deep": "#665353"
  },
  {
    "slug": "the-pillowcase-pair",
    "name": "The Pillowcase Pair",
    "sku": "EVERWELL-THEPILLOWCASEPAIR",
    "category": "Bundles",
    "shortBenefit": "Two pillowcases, one for each side.",
    "description": "[[PLACEHOLDER]] Two pillowcases, one for each side. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Pillowcase Pair from Lunelle Silk. Two pillowcases, one for each side.",
    "price": 159,
    "compareAt": 198,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 920,
    "badge": "Buy 2 & Save",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "Two 22-momme pillowcases",
      "Mix or match the colours",
      "Arrives gift-boxed"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Wash cool on a delicate cycle, hang to dry.",
    "image": "images/products/the-pillowcase-pair.svg",
    "gallery": [
      "images/products/the-pillowcase-pair.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Pillowcase Pair]]",
    "swatch": "#e4e6ea",
    "colour": "Pearl",
    "tint": "#fbfcfc",
    "deep": "#676769"
  },
  {
    "slug": "the-gift-box",
    "name": "The Gift Box",
    "sku": "EVERWELL-THEGIFTBOX",
    "category": "Bundles",
    "shortBenefit": "The whole range, boxed and ribboned.",
    "description": "[[PLACEHOLDER]] The whole range, boxed and ribboned. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Gift Box from Lunelle Silk. The whole range, boxed and ribboned.",
    "price": 199,
    "compareAt": 254,
    "priceNote": null,
    "rating": 5,
    "reviewCount": 540,
    "badge": "Save 22%",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "Pillowcase, mask, scrunchies and a travel pouch",
      "Gift box and ribbon included",
      "Add a handwritten note at checkout"
    ],
    "ingredients": [
      "100% mulberry silk throughout"
    ],
    "howItWorks": "Follow the care label on each piece.",
    "image": "images/products/the-gift-box.svg",
    "gallery": [
      "images/products/the-gift-box.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Gift Box]]",
    "swatch": "#dfc68c",
    "colour": "Gold",
    "tint": "#fbf7ef",
    "deep": "#64593f"
  },
  {
    "slug": "the-deluxe-silk-set",
    "name": "The Deluxe Silk Set",
    "sku": "EVERWELL-THEDELUXESILKSET",
    "category": "Bundles",
    "shortBenefit": "Two pillowcases, two masks, and 6 scrunchies.",
    "description": "[[PLACEHOLDER]] Two pillowcases, two masks, and 6 scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Deluxe Silk Set from Lunelle Silk. Two pillowcases, two masks, and 6 scrunchies.",
    "price": 229,
    "compareAt": 289,
    "priceNote": null,
    "rating": 5,
    "reviewCount": 780,
    "badge": "Save 25%",
    "featured": true,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "Complete set for couples",
      "Premium gift box presentation",
      "Maximum savings bundle"
    ],
    "ingredients": [
      "100% mulberry silk throughout"
    ],
    "howItWorks": "Unbox and enjoy total silk luxury.",
    "image": "images/products/the-deluxe-silk-set.svg",
    "gallery": [
      "images/products/the-deluxe-silk-set.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Deluxe Silk Set]]",
    "swatch": "#2a3350",
    "colour": "Midnight",
    "tint": "#e1e2e7",
    "deep": "#131724"
  },
  {
    "slug": "the-travel-companion",
    "name": "The Travel Companion Set",
    "sku": "EVERWELL-THETRAVELCOMPANION",
    "category": "Bundles",
    "shortBenefit": "Sleep mask, scrunchie & silk travel pouch.",
    "description": "[[PLACEHOLDER]] Sleep mask, scrunchie & silk travel pouch. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Travel Companion Set from Lunelle Silk. Sleep mask, scrunchie & silk travel pouch.",
    "price": 89,
    "compareAt": 115,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 640,
    "badge": "Travel Pack",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "One size"
    ],
    "benefits": [
      "Includes silk mask & scrunchie",
      "Custom compact carry pouch",
      "Ideal for flights and hotel stays"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Pack in carry-on bag.",
    "image": "images/products/the-travel-companion.svg",
    "gallery": [
      "images/products/the-travel-companion.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Travel Companion Set]]",
    "swatch": "#e8dcc6",
    "colour": "Champagne",
    "tint": "#fcfaf7",
    "deep": "#686359"
  },
  {
    "slug": "the-weekend-luxe-bundle",
    "name": "The Weekend Luxe Bundle",
    "sku": "EVERWELL-THEWEEKENDLUXEBUNDLE",
    "category": "Bundles",
    "shortBenefit": "Pillowcase & sleep mask in soothing Sage.",
    "description": "[[PLACEHOLDER]] Pillowcase & sleep mask in soothing Sage. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Weekend Luxe Bundle from Lunelle Silk. Pillowcase & sleep mask in soothing Sage.",
    "price": 119,
    "compareAt": 148,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 490,
    "badge": "Save 20%",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "Color-matched pillowcase & mask",
      "22-momme mulberry silk",
      "Gift packaging"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Wash cool, dry in shade.",
    "image": "images/products/the-weekend-luxe-bundle.svg",
    "gallery": [
      "images/products/the-weekend-luxe-bundle.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Weekend Luxe Bundle]]",
    "swatch": "#cdd8c8",
    "colour": "Sage",
    "tint": "#f8faf7",
    "deep": "#5c615a"
  },
  {
    "slug": "the-bedtime-essentials",
    "name": "The Bedtime Essentials Bundle",
    "sku": "EVERWELL-THEBEDTIMEESSENTIALS",
    "category": "Bundles",
    "shortBenefit": "Pillowcase and set of 3 scrunchies.",
    "description": "[[PLACEHOLDER]] Pillowcase and set of 3 scrunchies. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Bedtime Essentials Bundle from Lunelle Silk. Pillowcase and set of 3 scrunchies.",
    "price": 109,
    "compareAt": 135,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 870,
    "badge": "Popular",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "Ivory pillowcase with matching scrunchies",
      "Protects hair and skin overnight",
      "Delicate wash approved"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Use daily for skin and hair health.",
    "image": "images/products/the-bedtime-essentials.svg",
    "gallery": [
      "images/products/the-bedtime-essentials.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Bedtime Essentials Bundle]]",
    "swatch": "#f2ece1",
    "colour": "Ivory",
    "tint": "#fdfcfb",
    "deep": "#6d6a65"
  },
  {
    "slug": "the-silk-trio-pack",
    "name": "The Silk Trio Pack",
    "sku": "EVERWELL-THESILKTRIOPACK",
    "category": "Bundles",
    "shortBenefit": "Three silk pillowcases in pastel tones.",
    "description": "[[PLACEHOLDER]] Three silk pillowcases in pastel tones. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Silk Trio Pack from Lunelle Silk. Three silk pillowcases in pastel tones.",
    "price": 239,
    "compareAt": 297,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 350,
    "badge": "Best Value",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "Three pillowcases in Lavender, Sage, Pearl",
      "Save $58 vs buying individual items",
      "Great for laundry rotation"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Rotate weekly for fresh sleep.",
    "image": "images/products/the-silk-trio-pack.svg",
    "gallery": [
      "images/products/the-silk-trio-pack.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Silk Trio Pack]]",
    "swatch": "#d8d2e6",
    "colour": "Lavender",
    "tint": "#faf9fc",
    "deep": "#615e67"
  },
  {
    "slug": "the-ultimate-glow-kit",
    "name": "The Ultimate Glow Kit",
    "sku": "EVERWELL-THEULTIMATEGLOWKIT",
    "category": "Bundles",
    "shortBenefit": "Blush pillowcase, sleep mask, and face band.",
    "description": "[[PLACEHOLDER]] Blush pillowcase, sleep mask, and face band. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Ultimate Glow Kit from Lunelle Silk. Blush pillowcase, sleep mask, and face band.",
    "price": 149,
    "compareAt": 185,
    "priceNote": null,
    "rating": 4.9,
    "reviewCount": 520,
    "badge": "Gift Choice",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "Complete night skin routine kit",
      "Ultra gentle on sensitive skin",
      "Beautiful gift presentation"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Incorporate into nighttime beauty ritual.",
    "image": "images/products/the-ultimate-glow-kit.svg",
    "gallery": [
      "images/products/the-ultimate-glow-kit.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Ultimate Glow Kit]]",
    "swatch": "#edd3d1",
    "colour": "Blush",
    "tint": "#fcf9f9",
    "deep": "#6b5f5e"
  },
  {
    "slug": "the-double-pillowcase-mask-set",
    "name": "The Double Pillowcase & Mask Set",
    "sku": "EVERWELL-THEDOUBLEPILLOWCASEMASKSET",
    "category": "Bundles",
    "shortBenefit": "2 Charcoal pillowcases + 2 Charcoal sleep masks.",
    "description": "[[PLACEHOLDER]] 2 Charcoal pillowcases + 2 Charcoal sleep masks. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Double Pillowcase & Mask Set from Lunelle Silk. 2 Charcoal pillowcases + 2 Charcoal sleep masks.",
    "price": 185,
    "compareAt": 235,
    "priceNote": null,
    "rating": 4.8,
    "reviewCount": 410,
    "badge": "Save 21%",
    "featured": false,
    "optionLabel": "Size",
    "options": [
      "Standard",
      "Queen",
      "King"
    ],
    "benefits": [
      "Set of 2 pillowcases and 2 masks",
      "Matching deep charcoal aesthetic",
      "Hypoallergenic and breathable"
    ],
    "ingredients": [
      "100% mulberry silk"
    ],
    "howItWorks": "Machine wash cool.",
    "image": "images/products/the-double-pillowcase-mask-set.svg",
    "gallery": [
      "images/products/the-double-pillowcase-mask-set.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Double Pillowcase & Mask Set]]",
    "swatch": "#4a4e58",
    "colour": "Charcoal",
    "tint": "#e6e6e8",
    "deep": "#212328"
  }
];

/* ==========================================================================
   CATEGORIES
   The order categories appear in, and an optional line about each. Membership
   is not here: a product's own category field decides that. A category with no
   products in it is not shown, whatever this list says.
   ========================================================================== */

var CATEGORIES = [
  {
    "name": "Pillowcases",
    "slug": "pillowcases",
    "blurb": ""
  },
  {
    "name": "Sleep Masks",
    "slug": "sleep-masks",
    "blurb": ""
  },
  {
    "name": "Scrunchies",
    "slug": "scrunchies",
    "blurb": ""
  },
  {
    "name": "Bundles",
    "slug": "bundles",
    "blurb": ""
  }
];

/* ==========================================================================
   COLLECTIONS
   Hand-picked sets of products, which may cut across categories. Each one is
   served by collection.html?c=<slug>. Empty here: collections are made in
   admin.html, which writes them into js/products.js.
   ========================================================================== */

var COLLECTIONS = [];

/* ========================================================================== */

var TESTIMONIALS = [
  {
    "name": "Amelia R.",
    "role": "Verified buyer",
    "rating": 5,
    "quote": "I bought one to try and ordered three more the same week. My hair is noticeably less of a mess in the morning.",
    "avatar": "images/avatars/avatar-1.svg"
  },
  {
    "name": "Priya S.",
    "role": "Verified buyer",
    "rating": 5,
    "quote": "It washes beautifully. Six months in and the champagne one still looks like it did on day one.",
    "avatar": "images/avatars/avatar-2.svg"
  },
  {
    "name": "Daniel K.",
    "role": "Verified buyer",
    "rating": 5,
    "quote": "Bought the midnight as a gift and ended up keeping it. Ordered two more.",
    "avatar": "images/avatars/avatar-3.svg"
  },
  {
    "name": "Hana M.",
    "role": "Verified buyer",
    "rating": 4,
    "quote": "The zip is the detail that sold me — nothing slides off in the night.",
    "avatar": "images/avatars/avatar-4.svg"
  },
  {
    "name": "Grace L.",
    "role": "Verified buyer",
    "rating": 5,
    "quote": "The gift box arrived looking genuinely expensive. I did not need to wrap anything.",
    "avatar": "images/avatars/avatar-5.svg"
  },
  {
    "name": "Sofia T.",
    "role": "Verified buyer",
    "rating": 5,
    "quote": "Sleep mask and pillowcase in the same colour. Small thing, but it looks considered.",
    "avatar": "images/avatars/avatar-6.svg"
  },
  {
    "name": "Noor A.",
    "role": "Verified buyer",
    "rating": 5,
    "quote": "Delivery was quicker than the estimate and the packaging was lovely.",
    "avatar": "images/avatars/avatar-7.svg"
  },
  {
    "name": "Elena V.",
    "role": "Verified buyer",
    "rating": 4,
    "quote": "I was sceptical about the price. Having slept on it for a month, I get it now.",
    "avatar": "images/avatars/avatar-8.svg"
  }
];

/* Shown above the reviews. Replace with real aggregate numbers, or delete the
   block from index.html — invented ratings must not reach structured data. */
var REVIEWS_SUMMARY = {
  "rating": 4.9,
  "count": "[[PLACEHOLDER: 230,000]]",
  "promo": {
    "pill": "Award",
    "text": "[[PLACEHOLDER]] Most gifted product three years running —",
    "linkText": "Read all reviews",
    "href": "shop.html"
  }
};

var FAQS = [
  {
    "q": "What does 22-momme mean?",
    "a": "Momme measures the weight of silk. 22 is the point where it feels substantial and survives washing — thinner silk is cheaper to make and wears out faster."
  },
  {
    "q": "Which size do I need?",
    "a": "Standard fits most pillows. Queen is a little longer, King noticeably so. If your pillow is deep, size up — the case should slip on without stretching."
  },
  {
    "q": "How do I wash it?",
    "a": "Cool delicate cycle with a mild detergent, ideally in a mesh bag, then hang to dry. No tumble dryer, no bleach, no dry cleaning."
  },
  {
    "q": "Is it silk on both sides?",
    "a": "Yes. Both faces are the same 22-momme mulberry silk. Some pillowcases are silk on one side and cotton on the other — ours are not."
  },
  {
    "q": "What is the zip for?",
    "a": "It keeps the case on the pillow overnight and stops it working loose in the wash. It sits hidden along one edge."
  },
  {
    "q": "Can I try it first?",
    "a": "Sixty nights. Sleep on it, wash it, and if it is not for you send it back for a refund."
  },
  {
    "q": "Do the colours fade?",
    "a": "The dyes are OEKO-TEX certified and set for washing. Wash cool and dry out of direct sun and the colour holds."
  },
  {
    "q": "How long does delivery take?",
    "a": "[[PLACEHOLDER: confirm real timings]] Orders are packed within a business day. Delivery estimates are shown at checkout, and every order is tracked."
  }
];
