/* ==========================================================================
   BRAND-CONFIG.JS — Lumen Skin

   >>> THIS IS THE ONLY FILE YOU NEED TO EDIT. <<<

   Everything below drives the whole site: brand name, colours, products,
   prices, testimonials, FAQs, and the Shopify redirect links.

   TO GO LIVE, YOU MUST:
     1. Replace every checkoutUrl with the real Shopify product URL.
     2. Replace every [[PLACEHOLDER: ...]] string.
     3. Replace the images in images/ and images/products/ with real photos.
     4. Add real tracking IDs below and set tracking.enabled to true.
     5. Remove the noindex tag from every .html file (search for "noindex").

   Find every remaining placeholder at once:
     grep -rn "PLACEHOLDER" .           (Mac/Linux)
     findstr /s /n "PLACEHOLDER" *.*    (Windows)
   ========================================================================== */

var BRAND = {
  name: "Lumen Skin",
  tagline: "Considered skincare, without the ten-step routine.",
  announcement: "Complimentary shipping on orders over $50",
  logo: 'images/logo.svg',

  /* ---- Colours. theme-init.js applies these before first paint. -------- */
  colors: {
  "background": "#ffffff",
  "surface": "#faf5f1",
  "soft": "#f7efe8",
  "text": "#2e2723",
  "heading": "#241e1a",
  "muted": "#7a6b61",
  "border": "#eadfd6",
  "borderStrong": "#d6c4b6",
  "accent": "#b4573b",
  "accentHover": "#93442d",
  "accentTint": "#f8e9e3",
  "onAccent": "#ffffff",
  "footerBg": "#241e1a",
  "footerText": "#ded2c8",
  "star": "#c98a2e"
},

  style: {
  "radius": "4px",
  "radiusLarge": "6px",
  "buttonRadius": "4px",
  "cardStyle": "flat",
  "logoWidth": "148px"
},

  currency: {
  "symbol": "$",
  "code": "USD",
  "decimals": 2
},

  /* Every category has its own page. Generated by _tools/generate.js. */
  categoryPages: {
  "Cleanse": "cleanse.html",
  "Treat": "treat.html",
  "Moisturise": "moisturise.html",
  "Protect": "protect.html",
  "Sets": "sets.html"
},
  categoryIndex: {
  "Cleanse": 1,
  "Treat": 2,
  "Moisturise": 3,
  "Protect": 4,
  "Sets": 5
},
  categoryIcons: {},

  contact: {
    email: "hello@lumen-skin-placeholder.com",
    phone: "+1 (555) 010-8823",
    hours: "Mon–Fri, 9am–5pm ET",
    address: "[[PLACEHOLDER: registered business address]]",
    legalEntity: "Lumen Skin Co."
  },

  /* ---- Footer health disclaimer. Ad reviewers read this. --------------- */
  disclaimer: "[[PLACEHOLDER: health disclaimer]] The content on this site is for general information only and is not medical advice. Always speak to a qualified healthcare professional before starting, stopping or changing anything related to your health. Products are not intended to diagnose, treat, cure or prevent any disease.",

  copy: {
    buyCta: 'Buy now'
  },

  /* ---- Ad pixels. Nothing loads or fires until enabled is true. -------- */
  tracking: {
    enabled: false,
    ga4MeasurementId: '',            // 'G-XXXXXXXXXX'
    googleAdsConversionId: '',       // 'AW-XXXXXXXXX'
    googleAdsConversionLabel: '',    // the label from the conversion action
    metaPixelId: ''                  // numeric ID only
  },

  seo: {
    /* Leave false until a real review app supplies ratings. Invented ratings
       in structured data get Merchant Center accounts suspended. */
    emitAggregateRating: false
  },

  heroProof: [
  "Dermatologist-reviewed",
  "Cruelty-free",
  "Full ingredient lists"
],
  marquee: [
  "Free shipping over $50",
  "Plain, unbranded packaging",
  "30-day returns",
  "Cancel anytime",
  "Support replies in 24h",
  "Full ingredient lists"
],
  bento: [
  {
    "icon": "shield",
    "title": "Nothing hidden",
    "text": "[[PLACEHOLDER]] Every quantity printed on the label. No proprietary blends.",
    "wide": true
  },
  {
    "stat": "30",
    "title": "Day returns",
    "text": "[[PLACEHOLDER]] On unopened items.",
    "accent": true
  },
  {
    "icon": "box",
    "title": "Plain packaging",
    "text": "[[PLACEHOLDER]] No branding on the outside of any parcel."
  },
  {
    "icon": "chat",
    "title": "Real support",
    "text": "[[PLACEHOLDER]] A person replies within one business day."
  },
  {
    "icon": "refresh",
    "title": "Change anytime",
    "text": "[[PLACEHOLDER]] Pause, skip or cancel yourself."
  }
],
  compareOther: "Typical pharmacy",
  compare: [
  {
    "label": "Full ingredient quantities on the label",
    "us": true,
    "them": false
  },
  {
    "label": "Plain, unbranded outer packaging",
    "us": true,
    "them": false
  },
  {
    "label": "Pause or cancel without a phone call",
    "us": true,
    "them": false
  },
  {
    "label": "Delivered to your door",
    "us": true,
    "them": true
  }
],
  goals: [],
  spotlightSlug: "",
  promo: {
  "tag": "Limited offer",
  "heading": "[[PLACEHOLDER]] 15% off your first order",
  "text": "[[PLACEHOLDER]] Applies to everything in the range. One use per customer.",
  "code": "WELCOME15",
  "cta": "Shop the offer"
},
  valueProps: [
  {
    "icon": "leaf",
    "text": "Cruelty-free"
  },
  {
    "icon": "shield",
    "text": "Dermatologist-reviewed"
  },
  {
    "icon": "truck",
    "text": "Free shipping over $50"
  },
  {
    "icon": "refresh",
    "text": "30-day returns"
  }
],
  howItWorks: [
  {
    "title": "Take the routine quiz",
    "text": "[[PLACEHOLDER]] A few questions about your skin and what your mornings actually look like."
  },
  {
    "title": "Get a routine, not a catalogue",
    "text": "[[PLACEHOLDER]] We suggest the two or three products that fit, in the order to use them."
  },
  {
    "title": "Adjust as you go",
    "text": "[[PLACEHOLDER]] Change or pause deliveries whenever you like — no phone call required."
  }
],
  trustBadges: [
  {
    "icon": "stethoscope",
    "title": "Licensed providers",
    "text": "[[PLACEHOLDER: substantiate before launch]]"
  },
  {
    "icon": "lock",
    "title": "Secure checkout",
    "text": "Payments handled by an encrypted provider."
  },
  {
    "icon": "box",
    "title": "Discreet packaging",
    "text": "Plain outer packaging, no branding outside."
  },
  {
    "icon": "refresh",
    "title": "Money-back guarantee",
    "text": "[[PLACEHOLDER: confirm real terms]]"
  }
],
  productReassurance: [
  {
    "icon": "truck",
    "text": "Free shipping on orders over $50"
  },
  {
    "icon": "box",
    "text": "Plain, unbranded outer packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day return window on unopened items"
  },
  {
    "icon": "lock",
    "text": "Secure checkout"
  }
],
  values: [
  {
    "icon": "shield",
    "title": "Transparent by default",
    "text": "[[PLACEHOLDER]] Full ingredient lists and honest labelling on everything we sell."
  },
  {
    "icon": "stethoscope",
    "title": "Guided by professionals",
    "text": "[[PLACEHOLDER]] Our range is reviewed by qualified practitioners."
  },
  {
    "icon": "leaf",
    "title": "Thoughtfully sourced",
    "text": "[[PLACEHOLDER]] We work with suppliers who meet our quality standards."
  },
  {
    "icon": "chat",
    "title": "Support that answers",
    "text": "[[PLACEHOLDER]] Real people, replying within one business day."
  }
],
  stats: [
  {
    "value": "10k+",
    "label": "[[PLACEHOLDER]] orders delivered"
  },
  {
    "value": "4.8",
    "label": "[[PLACEHOLDER]] average rating"
  },
  {
    "value": "24h",
    "label": "[[PLACEHOLDER]] support response"
  },
  {
    "value": "30d",
    "label": "[[PLACEHOLDER]] returns window"
  }
],
  aboutPoints: [
  "[[PLACEHOLDER]] Every product reviewed before it joins the range",
  "[[PLACEHOLDER]] Clear ingredient lists, no proprietary blends",
  "[[PLACEHOLDER]] Plain packaging on every order",
  "[[PLACEHOLDER]] Cancel or change a subscription at any time"
]
};

/* ==========================================================================
   PRODUCTS
   checkoutUrl is the ONE integration point with your real Shopify store.
   Replace each one with the real product URL, e.g.
     'https://yourstore.com/products/daily-foundation'
   Buttons navigate there in the same tab after firing a tracking event.
   ========================================================================== */

var PRODUCTS = [
  {
    "slug": "gentle-gel-cleanser",
    "name": "Gentle Gel Cleanser",
    "sku": "LUMENSKIN-GENTLEGELCLE",
    "category": "Cleanse",
    "shortBenefit": "A morning and evening first step that does not strip.",
    "description": "[[PLACEHOLDER]] A morning and evening first step that does not strip. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Gentle Gel Cleanser from Lumen Skin. A morning and evening first step that does not strip.",
    "price": 28,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 894,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Fragrance-free",
      "Rinses clean",
      "150ml pump bottle"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Massage into damp skin and rinse. Use morning and evening, or as directed on the label.",
    "image": "images/products/gentle-gel-cleanser.svg",
    "gallery": [
      "images/products/gentle-gel-cleanser.svg",
      "images/products/_angle-cleanse-2.svg",
      "images/products/_angle-cleanse-3.svg",
      "images/products/_angle-cleanse-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Gentle Gel Cleanser]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/gentle-gel-cleanser"
  },
  {
    "slug": "hydrating-serum",
    "name": "Hydrating Serum",
    "sku": "LUMENSKIN-HYDRATINGSER",
    "category": "Treat",
    "shortBenefit": "The layer between cleansing and moisturising.",
    "description": "[[PLACEHOLDER]] The layer between cleansing and moisturising. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Hydrating Serum from Lumen Skin. The layer between cleansing and moisturising.",
    "price": 46,
    "compareAt": 58,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 1120,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Lightweight, absorbs quickly",
      "Layers under moisturiser",
      "30ml dropper bottle"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Apply a few drops to clean skin before moisturiser, as directed on the label.",
    "image": "images/products/hydrating-serum.svg",
    "gallery": [
      "images/products/hydrating-serum.svg",
      "images/products/_angle-treat-2.svg",
      "images/products/_angle-treat-3.svg",
      "images/products/_angle-treat-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Hydrating Serum]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/hydrating-serum"
  },
  {
    "slug": "daily-moisturiser",
    "name": "Daily Moisturiser",
    "sku": "LUMENSKIN-DAILYMOISTUR",
    "category": "Moisturise",
    "shortBenefit": "A final step that sits well under makeup.",
    "description": "[[PLACEHOLDER]] A final step that sits well under makeup. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Moisturiser from Lumen Skin. A final step that sits well under makeup.",
    "price": 38,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 742,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Non-greasy finish",
      "Fragrance-free",
      "50ml jar"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Apply to face and neck as the last step of your routine, as directed on the label.",
    "image": "images/products/daily-moisturiser.svg",
    "gallery": [
      "images/products/daily-moisturiser.svg",
      "images/products/_angle-moisturise-2.svg",
      "images/products/_angle-moisturise-3.svg",
      "images/products/_angle-moisturise-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Moisturiser]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-moisturiser"
  },
  {
    "slug": "daily-spf-40",
    "name": "Daily SPF 40",
    "sku": "LUMENSKIN-DAILYSPF40",
    "category": "Protect",
    "shortBenefit": "The step most routines skip.",
    "description": "[[PLACEHOLDER]] The step most routines skip. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily SPF 40 from Lumen Skin. The step most routines skip.",
    "price": 34,
    "compareAt": 42,
    "priceNote": "per 30-day supply",
    "rating": 4.6,
    "reviewCount": 566,
    "badge": "New",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "No white cast",
      "Wears well under makeup",
      "50ml tube"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Apply generously as the final morning step and reapply as directed on the label.",
    "image": "images/products/daily-spf-40.svg",
    "gallery": [
      "images/products/daily-spf-40.svg",
      "images/products/_angle-protect-2.svg",
      "images/products/_angle-protect-3.svg",
      "images/products/_angle-protect-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily SPF 40]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-spf-40"
  },
  {
    "slug": "overnight-recovery-balm",
    "name": "Overnight Recovery Balm",
    "sku": "LUMENSKIN-OVERNIGHTREC",
    "category": "Treat",
    "shortBenefit": "A richer option for the end of the day.",
    "description": "[[PLACEHOLDER]] A richer option for the end of the day. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Overnight Recovery Balm from Lumen Skin. A richer option for the end of the day.",
    "price": 52,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 318,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Richer evening texture",
      "A little goes a long way",
      "50ml jar"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Warm a small amount between fingertips and press into skin at night, as directed on the label.",
    "image": "images/products/overnight-recovery-balm.svg",
    "gallery": [
      "images/products/overnight-recovery-balm.svg",
      "images/products/_angle-treat-2.svg",
      "images/products/_angle-treat-3.svg",
      "images/products/_angle-treat-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Overnight Recovery Balm]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/overnight-recovery-balm"
  },
  {
    "slug": "the-core-routine",
    "name": "The Core Routine",
    "sku": "LUMENSKIN-THECOREROUTI",
    "category": "Sets",
    "shortBenefit": "Cleanser, serum, moisturiser and SPF, together.",
    "description": "[[PLACEHOLDER]] Cleanser, serum, moisturiser and SPF, together. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Core Routine from Lumen Skin. Cleanser, serum, moisturiser and SPF, together.",
    "price": 104,
    "compareAt": 138,
    "priceNote": "one-off purchase",
    "rating": 4.9,
    "reviewCount": 402,
    "badge": "Save 25%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "All four core steps",
      "Cheaper than buying separately",
      "Arrives in one box"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Use in order: cleanse, serum, moisturise, then SPF in the morning.",
    "image": "images/products/the-core-routine.svg",
    "gallery": [
      "images/products/the-core-routine.svg",
      "images/products/_angle-sets-2.svg",
      "images/products/_angle-sets-3.svg",
      "images/products/_angle-sets-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Core Routine]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/the-core-routine"
  }
];

/* ========================================================================== */

var TESTIMONIALS = [
  {
    "name": "Priya S.",
    "role": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] I went from seven products to three and my routine is genuinely easier to stick to now.",
    "avatar": "images/avatars/avatar-1.svg"
  },
  {
    "name": "Elena M.",
    "role": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] The texture is lovely and the ingredient list is printed where I can actually find it.",
    "avatar": "images/avatars/avatar-2.svg"
  },
  {
    "name": "Josie W.",
    "role": "[[PLACEHOLDER]] Verified customer",
    "rating": 4,
    "quote": "[[PLACEHOLDER]] Packaging is beautiful without being wasteful. Delivery was quick.",
    "avatar": "images/avatars/avatar-3.svg"
  }
];

/* Shown above the reviews. Replace with real aggregate numbers, or delete the
   block from index.html — invented ratings must not reach structured data. */
var REVIEWS_SUMMARY = {
  "rating": 4.8,
  "count": "[[PLACEHOLDER: review count]]"
};

var FAQS = [
  {
    "q": "How do I place an order?",
    "a": "[[PLACEHOLDER]] Choose the product you want and select Buy now. You will be taken to our secure store to complete checkout."
  },
  {
    "q": "How long does delivery take?",
    "a": "[[PLACEHOLDER: confirm real timings]] Orders are usually prepared for dispatch within a couple of business days. Delivery estimates are shown at checkout."
  },
  {
    "q": "Is the packaging discreet?",
    "a": "[[PLACEHOLDER]] Yes. Orders arrive in plain outer packaging with no product branding on the outside."
  },
  {
    "q": "Can I return something?",
    "a": "[[PLACEHOLDER: confirm real policy]] Unopened items can be returned within the window shown at checkout. Some health and personal care items cannot be returned once opened."
  },
  {
    "q": "Do you offer a subscription?",
    "a": "[[PLACEHOLDER]] Where a repeat option is available it is shown on the product page at checkout, and you can change or cancel it at any time."
  },
  {
    "q": "Should I speak to a healthcare professional first?",
    "a": "[[PLACEHOLDER]] If you are pregnant or breastfeeding, take prescription medicine, or have an existing medical condition, speak to a qualified healthcare professional before starting anything new. See our medical disclaimer."
  },
  {
    "q": "How do I contact support?",
    "a": "[[PLACEHOLDER]] Use the contact form, or email us directly. We aim to reply within one business day."
  },
  {
    "q": "Where do you ship?",
    "a": "[[PLACEHOLDER: list real destinations]] Shipping destinations and rates are shown at checkout."
  }
];
