/* ==========================================================================
   BRAND-CONFIG.JS — Balance Co

   >>> THIS IS THE ONLY FILE YOU NEED TO EDIT. <<<

   Everything below drives the whole site: brand name, colours, products,
   prices, testimonials, FAQs, and the Shopify redirect links.

   TO GO LIVE, YOU MUST:
     1. Replace every checkoutUrl with the real Shopify product URL.
     2. Replace every [[PLACEHOLDER: ...]] string.
     3. Replace the images in images/ and images/products/ with real photos.
     4. Add real tracking IDs below and set tracking.enabled to true.
     5. Remove the noindex tag from every .html file (search for "noindex").

   Find every remaining placeholder at once:
     grep -rn "PLACEHOLDER" .           (Mac/Linux)
     findstr /s /n "PLACEHOLDER" *.*    (Windows)
   ========================================================================== */

var BRAND = {
  name: "Balance Co",
  tagline: "Support for the goals you set yourself.",
  announcement: "Free shipping over $50 · Plain packaging on every order",
  logo: 'images/logo.svg',

  /* ---- Colours. theme-init.js applies these before first paint. -------- */
  colors: {
  "background": "#ffffff",
  "surface": "#f3f7f2",
  "soft": "#eef3ec",
  "text": "#1f2a24",
  "heading": "#16211b",
  "muted": "#5d6f64",
  "border": "#dee8dc",
  "borderStrong": "#c3d4c0",
  "accent": "#4a7c59",
  "accentHover": "#3a6246",
  "accentTint": "#e6f0e6",
  "onAccent": "#ffffff",
  "footerBg": "#16211b",
  "footerText": "#c8d6c9",
  "star": "#d29a2b"
},

  style: {
  "radius": "18px",
  "radiusLarge": "24px",
  "buttonRadius": "999px",
  "cardStyle": "elevated",
  "logoWidth": "150px"
},

  currency: {
  "symbol": "$",
  "code": "USD",
  "decimals": 2
},

  /* Every category has its own page. Generated by _tools/generate.js. */
  categoryPages: {
  "Daily support": "daily-support.html",
  "Nutrition": "nutrition.html",
  "Sleep": "sleep.html",
  "Bundles": "bundles.html"
},
  categoryIndex: {
  "Daily support": 1,
  "Nutrition": 2,
  "Sleep": 3,
  "Bundles": 4
},
  categoryIcons: {},

  contact: {
    email: "support@balance-co-placeholder.com",
    phone: "+1 (555) 010-6612",
    hours: "Mon–Sat, 8am–7pm ET",
    address: "[[PLACEHOLDER: registered business address]]",
    legalEntity: "Balance Co Wellness Ltd"
  },

  /* ---- Footer health disclaimer. Ad reviewers read this. --------------- */
  disclaimer: "[[PLACEHOLDER: health disclaimer]] The content on this site is for general information only and is not medical advice. Always speak to a qualified healthcare professional before starting, stopping or changing anything related to your health. Products are not intended to diagnose, treat, cure or prevent any disease.",

  copy: {
    buyCta: 'Buy now'
  },

  /* ---- Ad pixels. Nothing loads or fires until enabled is true. -------- */
  tracking: {
    enabled: false,
    ga4MeasurementId: '',            // 'G-XXXXXXXXXX'
    googleAdsConversionId: '',       // 'AW-XXXXXXXXX'
    googleAdsConversionLabel: '',    // the label from the conversion action
    metaPixelId: ''                  // numeric ID only
  },

  seo: {
    /* Leave false until a real review app supplies ratings. Invented ratings
       in structured data get Merchant Center accounts suspended. */
    emitAggregateRating: false
  },

  heroProof: [
  "No before-and-after photos",
  "Clear labelling",
  "Cancel anytime"
],
  marquee: [
  "Free shipping over $50",
  "Plain, unbranded packaging",
  "30-day returns",
  "Cancel anytime",
  "Support replies in 24h",
  "Full ingredient lists"
],
  bento: [
  {
    "icon": "shield",
    "title": "Nothing hidden",
    "text": "[[PLACEHOLDER]] Every quantity printed on the label. No proprietary blends.",
    "wide": true
  },
  {
    "stat": "30",
    "title": "Day returns",
    "text": "[[PLACEHOLDER]] On unopened items.",
    "accent": true
  },
  {
    "icon": "box",
    "title": "Plain packaging",
    "text": "[[PLACEHOLDER]] No branding on the outside of any parcel."
  },
  {
    "icon": "chat",
    "title": "Real support",
    "text": "[[PLACEHOLDER]] A person replies within one business day."
  },
  {
    "icon": "refresh",
    "title": "Change anytime",
    "text": "[[PLACEHOLDER]] Pause, skip or cancel yourself."
  }
],
  compareOther: "Typical pharmacy",
  compare: [
  {
    "label": "Full ingredient quantities on the label",
    "us": true,
    "them": false
  },
  {
    "label": "Plain, unbranded outer packaging",
    "us": true,
    "them": false
  },
  {
    "label": "Pause or cancel without a phone call",
    "us": true,
    "them": false
  },
  {
    "label": "Delivered to your door",
    "us": true,
    "them": true
  }
],
  valueProps: [
  {
    "icon": "shield",
    "text": "No inflated claims"
  },
  {
    "icon": "box",
    "text": "Plain packaging"
  },
  {
    "icon": "truck",
    "text": "Free shipping over $50"
  },
  {
    "icon": "refresh",
    "text": "Cancel anytime"
  }
],
  howItWorks: [
  {
    "title": "Take the quiz",
    "text": "[[PLACEHOLDER]] Two minutes of questions about your routine and what you are working towards."
  },
  {
    "title": "See what fits",
    "text": "[[PLACEHOLDER]] We suggest products that match, and tell you plainly when nothing does."
  },
  {
    "title": "Delivered on your schedule",
    "text": "[[PLACEHOLDER]] Choose how often it arrives. Pause or cancel whenever you want."
  }
],
  trustBadges: [
  {
    "icon": "stethoscope",
    "title": "Licensed providers",
    "text": "[[PLACEHOLDER: substantiate before launch]]"
  },
  {
    "icon": "lock",
    "title": "Secure checkout",
    "text": "Payments handled by an encrypted provider."
  },
  {
    "icon": "box",
    "title": "Discreet packaging",
    "text": "Plain outer packaging, no branding outside."
  },
  {
    "icon": "refresh",
    "title": "Money-back guarantee",
    "text": "[[PLACEHOLDER: confirm real terms]]"
  }
],
  productReassurance: [
  {
    "icon": "truck",
    "text": "Free shipping on orders over $50"
  },
  {
    "icon": "box",
    "text": "Plain, unbranded outer packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day return window on unopened items"
  },
  {
    "icon": "lock",
    "text": "Secure checkout"
  }
],
  values: [
  {
    "icon": "shield",
    "title": "Transparent by default",
    "text": "[[PLACEHOLDER]] Full ingredient lists and honest labelling on everything we sell."
  },
  {
    "icon": "stethoscope",
    "title": "Guided by professionals",
    "text": "[[PLACEHOLDER]] Our range is reviewed by qualified practitioners."
  },
  {
    "icon": "leaf",
    "title": "Thoughtfully sourced",
    "text": "[[PLACEHOLDER]] We work with suppliers who meet our quality standards."
  },
  {
    "icon": "chat",
    "title": "Support that answers",
    "text": "[[PLACEHOLDER]] Real people, replying within one business day."
  }
],
  stats: [
  {
    "value": "10k+",
    "label": "[[PLACEHOLDER]] orders delivered"
  },
  {
    "value": "4.8",
    "label": "[[PLACEHOLDER]] average rating"
  },
  {
    "value": "24h",
    "label": "[[PLACEHOLDER]] support response"
  },
  {
    "value": "30d",
    "label": "[[PLACEHOLDER]] returns window"
  }
],
  aboutPoints: [
  "[[PLACEHOLDER]] Every product reviewed before it joins the range",
  "[[PLACEHOLDER]] Clear ingredient lists, no proprietary blends",
  "[[PLACEHOLDER]] Plain packaging on every order",
  "[[PLACEHOLDER]] Cancel or change a subscription at any time"
]
};

/* ==========================================================================
   PRODUCTS
   checkoutUrl is the ONE integration point with your real Shopify store.
   Replace each one with the real product URL, e.g.
     'https://yourstore.com/products/daily-foundation'
   Buttons navigate there in the same tab after firing a tracking event.
   ========================================================================== */

var PRODUCTS = [
  {
    "slug": "daily-balance-capsules",
    "name": "Daily Balance Capsules",
    "sku": "BALANCECO-DAILYBALANCE",
    "category": "Daily support",
    "shortBenefit": "A once-daily capsule to sit alongside your routine.",
    "description": "[[PLACEHOLDER]] A once-daily capsule to sit alongside your routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Balance Capsules from Balance Co. A once-daily capsule to sit alongside your routine.",
    "price": 44,
    "compareAt": 55,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 523,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "One capsule per day",
      "30-day supply",
      "Full ingredient list on the label"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take as directed on the label. Speak to a healthcare professional before starting anything new.",
    "image": "images/products/daily-balance-capsules.svg",
    "gallery": [
      "images/products/daily-balance-capsules.svg",
      "images/products/_angle-daily-support-2.svg",
      "images/products/_angle-daily-support-3.svg",
      "images/products/_angle-daily-support-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Balance Capsules]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-balance-capsules"
  },
  {
    "slug": "fibre-blend",
    "name": "Daily Fibre Blend",
    "sku": "BALANCECO-FIBREBLEND",
    "category": "Daily support",
    "shortBenefit": "Mixes into water, coffee or a smoothie.",
    "description": "[[PLACEHOLDER]] Mixes into water, coffee or a smoothie. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Fibre Blend from Balance Co. Mixes into water, coffee or a smoothie.",
    "price": 36,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.6,
    "reviewCount": 388,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Unflavoured",
      "30 servings",
      "Dissolves without clumping"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Mix one serving into a drink as directed on the label.",
    "image": "images/products/fibre-blend.svg",
    "gallery": [
      "images/products/fibre-blend.svg",
      "images/products/_angle-daily-support-2.svg",
      "images/products/_angle-daily-support-3.svg",
      "images/products/_angle-daily-support-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Fibre Blend]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/fibre-blend"
  },
  {
    "slug": "protein-shake-vanilla",
    "name": "Protein Shake — Vanilla",
    "sku": "BALANCECO-PROTEINSHAKE",
    "category": "Nutrition",
    "shortBenefit": "A straightforward shake for busy mornings.",
    "description": "[[PLACEHOLDER]] A straightforward shake for busy mornings. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Protein Shake — Vanilla from Balance Co. A straightforward shake for busy mornings.",
    "price": 48,
    "compareAt": 58,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 671,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "20 servings per pouch",
      "Mixes with water or milk",
      "Also available unflavoured"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Blend one scoop with liquid of your choice as directed on the label.",
    "image": "images/products/protein-shake-vanilla.svg",
    "gallery": [
      "images/products/protein-shake-vanilla.svg",
      "images/products/_angle-nutrition-2.svg",
      "images/products/_angle-nutrition-3.svg",
      "images/products/_angle-nutrition-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Protein Shake — Vanilla]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/protein-shake-vanilla"
  },
  {
    "slug": "evening-calm",
    "name": "Evening Calm",
    "sku": "BALANCECO-EVENINGCALM",
    "category": "Sleep",
    "shortBenefit": "Formulated for the end of the day.",
    "description": "[[PLACEHOLDER]] Formulated for the end of the day. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Evening Calm from Balance Co. Formulated for the end of the day.",
    "price": 34,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.5,
    "reviewCount": 244,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Designed for evening use",
      "30-day supply",
      "Clearly labelled"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take in the evening as directed on the label.",
    "image": "images/products/evening-calm.svg",
    "gallery": [
      "images/products/evening-calm.svg",
      "images/products/_angle-sleep-2.svg",
      "images/products/_angle-sleep-3.svg",
      "images/products/_angle-sleep-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Evening Calm]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/evening-calm"
  },
  {
    "slug": "hydration-sticks",
    "name": "Hydration Sticks",
    "sku": "BALANCECO-HYDRATIONSTI",
    "category": "Nutrition",
    "shortBenefit": "Single-serve sticks for a water bottle.",
    "description": "[[PLACEHOLDER]] Single-serve sticks for a water bottle. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Hydration Sticks from Balance Co. Single-serve sticks for a water bottle.",
    "price": 26,
    "compareAt": 32,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 412,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "14 sticks per box",
      "Citrus flavour",
      "Fits in a pocket"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Add one stick to water as directed on the label.",
    "image": "images/products/hydration-sticks.svg",
    "gallery": [
      "images/products/hydration-sticks.svg",
      "images/products/_angle-nutrition-2.svg",
      "images/products/_angle-nutrition-3.svg",
      "images/products/_angle-nutrition-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Hydration Sticks]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/hydration-sticks"
  },
  {
    "slug": "balance-starter-kit",
    "name": "Balance Starter Kit",
    "sku": "BALANCECO-BALANCESTART",
    "category": "Bundles",
    "shortBenefit": "Three products to cover the basics of a routine.",
    "description": "[[PLACEHOLDER]] Three products to cover the basics of a routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Balance Starter Kit from Balance Co. Three products to cover the basics of a routine.",
    "price": 98,
    "compareAt": 128,
    "priceNote": "one-off purchase",
    "rating": 4.8,
    "reviewCount": 176,
    "badge": "Save 23%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Capsules, fibre blend and protein",
      "One delivery",
      "Pause or cancel anytime"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the label directions for each product in the kit.",
    "image": "images/products/balance-starter-kit.svg",
    "gallery": [
      "images/products/balance-starter-kit.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Balance Starter Kit]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/balance-starter-kit"
  }
];

/* ========================================================================== */

var TESTIMONIALS = [
  {
    "name": "Rachel K.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] The thing that sold me was the absence of hype. It reads like a normal shop, not a pitch."
  },
  {
    "name": "Tom A.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 4,
    "quote": "[[PLACEHOLDER]] Easy to pause when I went travelling and just as easy to restart. No phone calls."
  },
  {
    "name": "Nadia B.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] Clear labels, quick delivery, and the packaging gives nothing away."
  }
];

var FAQS = [
  {
    "q": "How do I place an order?",
    "a": "[[PLACEHOLDER]] Choose the product you want and select Buy now. You will be taken to our secure store to complete checkout."
  },
  {
    "q": "How long does delivery take?",
    "a": "[[PLACEHOLDER: confirm real timings]] Orders are usually prepared for dispatch within a couple of business days. Delivery estimates are shown at checkout."
  },
  {
    "q": "Is the packaging discreet?",
    "a": "[[PLACEHOLDER]] Yes. Orders arrive in plain outer packaging with no product branding on the outside."
  },
  {
    "q": "Can I return something?",
    "a": "[[PLACEHOLDER: confirm real policy]] Unopened items can be returned within the window shown at checkout. Some health and personal care items cannot be returned once opened."
  },
  {
    "q": "Do you offer a subscription?",
    "a": "[[PLACEHOLDER]] Where a repeat option is available it is shown on the product page at checkout, and you can change or cancel it at any time."
  },
  {
    "q": "Should I speak to a healthcare professional first?",
    "a": "[[PLACEHOLDER]] If you are pregnant or breastfeeding, take prescription medicine, or have an existing medical condition, speak to a qualified healthcare professional before starting anything new. See our medical disclaimer."
  },
  {
    "q": "How do I contact support?",
    "a": "[[PLACEHOLDER]] Use the contact form, or email us directly. We aim to reply within one business day."
  },
  {
    "q": "Where do you ship?",
    "a": "[[PLACEHOLDER: list real destinations]] Shipping destinations and rates are shown at checkout."
  }
];
