/* ==========================================================================
   BRAND-CONFIG.JS — Nova Daily

   >>> THIS IS THE ONLY FILE YOU NEED TO EDIT. <<<

   Everything below drives the whole site: brand name, colours, products,
   prices, testimonials, FAQs, and the Shopify redirect links.

   TO GO LIVE, YOU MUST:
     1. Replace every checkoutUrl with the real Shopify product URL.
     2. Replace every [[PLACEHOLDER: ...]] string.
     3. Replace the images in images/ and images/products/ with real photos.
     4. Add real tracking IDs below and set tracking.enabled to true.
     5. Remove the noindex tag from every .html file (search for "noindex").

   Find every remaining placeholder at once:
     grep -rn "PLACEHOLDER" .           (Mac/Linux)
     findstr /s /n "PLACEHOLDER" *.*    (Windows)
   ========================================================================== */

var BRAND = {
  name: "Nova Daily",
  tagline: "The daily basics, done properly.",
  announcement: "Free shipping over $50 · Subscribe and save 15%",
  logo: 'images/logo.svg',

  /* ---- Colours. theme-init.js applies these before first paint. -------- */
  colors: {
  "background": "#fffdfa",
  "surface": "#faf3e9",
  "soft": "#f8f1e6",
  "text": "#2a2318",
  "heading": "#1f1a12",
  "muted": "#7a6b56",
  "border": "#ece0cd",
  "borderStrong": "#d8c5a8",
  "accent": "#a06a1f",
  "accentHover": "#835616",
  "accentTint": "#f6ead6",
  "onAccent": "#ffffff",
  "footerBg": "#1f1a12",
  "footerText": "#ddd0bb",
  "star": "#c98a2e"
},

  style: {
  "radius": "10px",
  "radiusLarge": "12px",
  "buttonRadius": "6px",
  "cardStyle": "bordered",
  "logoWidth": "152px"
},

  currency: {
  "symbol": "$",
  "code": "USD",
  "decimals": 2
},

  /* Every category has its own page. Generated by _tools/generate.js. */
  categoryPages: {
  "Foundations": "foundations.html",
  "Evening": "evening.html",
  "Blends": "blends.html",
  "Bundles": "bundles.html"
},
  categoryIndex: {
  "Foundations": 1,
  "Evening": 2,
  "Blends": 3,
  "Bundles": 4
},
  categoryIcons: {},

  contact: {
    email: "hello@nova-daily-placeholder.com",
    phone: "+1 (555) 010-2290",
    hours: "Mon–Fri, 9am–6pm ET",
    address: "[[PLACEHOLDER: registered business address]]",
    legalEntity: "Nova Daily Nutrition Inc."
  },

  /* ---- Footer health disclaimer. Ad reviewers read this. --------------- */
  disclaimer: "[[PLACEHOLDER: health disclaimer]] The content on this site is for general information only and is not medical advice. Always speak to a qualified healthcare professional before starting, stopping or changing anything related to your health. Products are not intended to diagnose, treat, cure or prevent any disease.",

  copy: {
    buyCta: 'Buy now'
  },

  /* ---- Ad pixels. Nothing loads or fires until enabled is true. -------- */
  tracking: {
    enabled: false,
    ga4MeasurementId: '',            // 'G-XXXXXXXXXX'
    googleAdsConversionId: '',       // 'AW-XXXXXXXXX'
    googleAdsConversionLabel: '',    // the label from the conversion action
    metaPixelId: ''                  // numeric ID only
  },

  seo: {
    /* Leave false until a real review app supplies ratings. Invented ratings
       in structured data get Merchant Center accounts suspended. */
    emitAggregateRating: false
  },

  heroProof: [
  "Third-party tested",
  "No proprietary blends",
  "Subscribe and save"
],
  marquee: [
  "Free shipping over $50",
  "Plain, unbranded packaging",
  "30-day returns",
  "Cancel anytime",
  "Support replies in 24h",
  "Full ingredient lists"
],
  bento: [
  {
    "icon": "shield",
    "title": "Nothing hidden",
    "text": "[[PLACEHOLDER]] Every quantity printed on the label. No proprietary blends.",
    "wide": true
  },
  {
    "stat": "30",
    "title": "Day returns",
    "text": "[[PLACEHOLDER]] On unopened items.",
    "accent": true
  },
  {
    "icon": "box",
    "title": "Plain packaging",
    "text": "[[PLACEHOLDER]] No branding on the outside of any parcel."
  },
  {
    "icon": "chat",
    "title": "Real support",
    "text": "[[PLACEHOLDER]] A person replies within one business day."
  },
  {
    "icon": "refresh",
    "title": "Change anytime",
    "text": "[[PLACEHOLDER]] Pause, skip or cancel yourself."
  }
],
  compareOther: "Typical pharmacy",
  compare: [
  {
    "label": "Full ingredient quantities on the label",
    "us": true,
    "them": false
  },
  {
    "label": "Plain, unbranded outer packaging",
    "us": true,
    "them": false
  },
  {
    "label": "Pause or cancel without a phone call",
    "us": true,
    "them": false
  },
  {
    "label": "Delivered to your door",
    "us": true,
    "them": true
  }
],
  goals: [],
  spotlightSlug: "",
  promo: {
  "tag": "Limited offer",
  "heading": "[[PLACEHOLDER]] 15% off your first order",
  "text": "[[PLACEHOLDER]] Applies to everything in the range. One use per customer.",
  "code": "WELCOME15",
  "cta": "Shop the offer"
},
  valueProps: [
  {
    "icon": "shield",
    "text": "Third-party tested"
  },
  {
    "icon": "leaf",
    "text": "Full disclosure labels"
  },
  {
    "icon": "truck",
    "text": "Free shipping over $50"
  },
  {
    "icon": "refresh",
    "text": "Cancel anytime"
  }
],
  howItWorks: [
  {
    "title": "Pick your products",
    "text": "[[PLACEHOLDER]] Browse the range and choose what fits your routine. No quiz required."
  },
  {
    "title": "Choose a schedule",
    "text": "[[PLACEHOLDER]] One-off order, or a repeat delivery at 15% off. Change it whenever."
  },
  {
    "title": "It arrives, quietly",
    "text": "[[PLACEHOLDER]] Plain outer packaging, on the schedule you picked."
  }
],
  trustBadges: [
  {
    "icon": "stethoscope",
    "title": "Licensed providers",
    "text": "[[PLACEHOLDER: substantiate before launch]]"
  },
  {
    "icon": "lock",
    "title": "Secure checkout",
    "text": "Payments handled by an encrypted provider."
  },
  {
    "icon": "box",
    "title": "Discreet packaging",
    "text": "Plain outer packaging, no branding outside."
  },
  {
    "icon": "refresh",
    "title": "Money-back guarantee",
    "text": "[[PLACEHOLDER: confirm real terms]]"
  }
],
  productReassurance: [
  {
    "icon": "truck",
    "text": "Free shipping on orders over $50"
  },
  {
    "icon": "box",
    "text": "Plain, unbranded outer packaging"
  },
  {
    "icon": "refresh",
    "text": "30-day return window on unopened items"
  },
  {
    "icon": "lock",
    "text": "Secure checkout"
  }
],
  values: [
  {
    "icon": "shield",
    "title": "Transparent by default",
    "text": "[[PLACEHOLDER]] Full ingredient lists and honest labelling on everything we sell."
  },
  {
    "icon": "stethoscope",
    "title": "Guided by professionals",
    "text": "[[PLACEHOLDER]] Our range is reviewed by qualified practitioners."
  },
  {
    "icon": "leaf",
    "title": "Thoughtfully sourced",
    "text": "[[PLACEHOLDER]] We work with suppliers who meet our quality standards."
  },
  {
    "icon": "chat",
    "title": "Support that answers",
    "text": "[[PLACEHOLDER]] Real people, replying within one business day."
  }
],
  stats: [
  {
    "value": "10k+",
    "label": "[[PLACEHOLDER]] orders delivered"
  },
  {
    "value": "4.8",
    "label": "[[PLACEHOLDER]] average rating"
  },
  {
    "value": "24h",
    "label": "[[PLACEHOLDER]] support response"
  },
  {
    "value": "30d",
    "label": "[[PLACEHOLDER]] returns window"
  }
],
  aboutPoints: [
  "[[PLACEHOLDER]] Every product reviewed before it joins the range",
  "[[PLACEHOLDER]] Clear ingredient lists, no proprietary blends",
  "[[PLACEHOLDER]] Plain packaging on every order",
  "[[PLACEHOLDER]] Cancel or change a subscription at any time"
]
};

/* ==========================================================================
   PRODUCTS
   checkoutUrl is the ONE integration point with your real Shopify store.
   Replace each one with the real product URL, e.g.
     'https://yourstore.com/products/daily-foundation'
   Buttons navigate there in the same tab after firing a tracking event.
   ========================================================================== */

var PRODUCTS = [
  {
    "slug": "daily-multi",
    "name": "Daily Multi",
    "sku": "NOVADAILY-DAILYMULTI",
    "category": "Foundations",
    "shortBenefit": "One capsule covering the everyday basics.",
    "description": "[[PLACEHOLDER]] One capsule covering the everyday basics. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Daily Multi from Nova Daily. One capsule covering the everyday basics.",
    "price": 32,
    "compareAt": 40,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 1340,
    "badge": "Best seller",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Every quantity printed on the label",
      "Third-party tested batches",
      "30-day supply"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take one capsule daily with food, as directed on the label.",
    "image": "images/products/daily-multi.svg",
    "gallery": [
      "images/products/daily-multi.svg",
      "images/products/_angle-foundations-2.svg",
      "images/products/_angle-foundations-3.svg",
      "images/products/_angle-foundations-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Daily Multi]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/daily-multi"
  },
  {
    "slug": "omega-3",
    "name": "Omega-3",
    "sku": "NOVADAILY-OMEGA3",
    "category": "Foundations",
    "shortBenefit": "A daily softgel with no aftertaste.",
    "description": "[[PLACEHOLDER]] A daily softgel with no aftertaste. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Omega-3 from Nova Daily. A daily softgel with no aftertaste.",
    "price": 34,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.7,
    "reviewCount": 806,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Third-party tested for purity",
      "60 softgels",
      "Full disclosure label"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take as directed on the label, ideally with a meal.",
    "image": "images/products/omega-3.svg",
    "gallery": [
      "images/products/omega-3.svg",
      "images/products/_angle-foundations-2.svg",
      "images/products/_angle-foundations-3.svg",
      "images/products/_angle-foundations-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Omega-3]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/omega-3"
  },
  {
    "slug": "magnesium-evening",
    "name": "Magnesium Evening",
    "sku": "NOVADAILY-MAGNESIUMEVE",
    "category": "Evening",
    "shortBenefit": "Made to be the last thing in your routine.",
    "description": "[[PLACEHOLDER]] Made to be the last thing in your routine. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Magnesium Evening from Nova Daily. Made to be the last thing in your routine.",
    "price": 28,
    "compareAt": 34,
    "priceNote": "per 30-day supply",
    "rating": 4.8,
    "reviewCount": 923,
    "badge": null,
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Designed for evening use",
      "60 capsules",
      "Third-party tested"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take in the evening as directed on the label.",
    "image": "images/products/magnesium-evening.svg",
    "gallery": [
      "images/products/magnesium-evening.svg",
      "images/products/_angle-evening-2.svg",
      "images/products/_angle-evening-3.svg",
      "images/products/_angle-evening-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Magnesium Evening]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/magnesium-evening"
  },
  {
    "slug": "vitamin-d3-k2",
    "name": "Vitamin D3 + K2",
    "sku": "NOVADAILY-VITAMIND3K2",
    "category": "Foundations",
    "shortBenefit": "A small daily drop, easy to remember.",
    "description": "[[PLACEHOLDER]] A small daily drop, easy to remember. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Vitamin D3 + K2 from Nova Daily. A small daily drop, easy to remember.",
    "price": 26,
    "compareAt": null,
    "priceNote": "per 30-day supply",
    "rating": 4.9,
    "reviewCount": 655,
    "badge": "New",
    "featured": true,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Liquid drops, no capsule",
      "60-day supply",
      "Third-party tested"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Take the number of drops stated on the label, with food.",
    "image": "images/products/vitamin-d3-k2.svg",
    "gallery": [
      "images/products/vitamin-d3-k2.svg",
      "images/products/_angle-foundations-2.svg",
      "images/products/_angle-foundations-3.svg",
      "images/products/_angle-foundations-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Vitamin D3 + K2]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/vitamin-d3-k2"
  },
  {
    "slug": "greens-powder",
    "name": "Greens Powder",
    "sku": "NOVADAILY-GREENSPOWDER",
    "category": "Blends",
    "shortBenefit": "A daily scoop for water or a smoothie.",
    "description": "[[PLACEHOLDER]] A daily scoop for water or a smoothie. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] Greens Powder from Nova Daily. A daily scoop for water or a smoothie.",
    "price": 42,
    "compareAt": 52,
    "priceNote": "per 30-day supply",
    "rating": 4.4,
    "reviewCount": 377,
    "badge": null,
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "30 servings",
      "Mild flavour",
      "Every ingredient quantified"
    ],
    "ingredients": [
      "[[PLACEHOLDER: ingredient one]]",
      "[[PLACEHOLDER: ingredient two]]",
      "[[PLACEHOLDER: ingredient three]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Mix one scoop into liquid as directed on the label.",
    "image": "images/products/greens-powder.svg",
    "gallery": [
      "images/products/greens-powder.svg",
      "images/products/_angle-blends-2.svg",
      "images/products/_angle-blends-3.svg",
      "images/products/_angle-blends-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of Greens Powder]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/greens-powder"
  },
  {
    "slug": "the-daily-three",
    "name": "The Daily Three",
    "sku": "NOVADAILY-THEDAILYTHRE",
    "category": "Bundles",
    "shortBenefit": "Multi, Omega-3 and Magnesium in one subscription.",
    "description": "[[PLACEHOLDER]] Multi, Omega-3 and Magnesium in one subscription. Full product copy goes here — keep it factual and avoid medical claims until reviewed.",
    "metaDescription": "[[PLACEHOLDER]] The Daily Three from Nova Daily. Multi, Omega-3 and Magnesium in one subscription.",
    "price": 82,
    "compareAt": 106,
    "priceNote": "one-off purchase",
    "rating": 4.9,
    "reviewCount": 289,
    "badge": "Save 22%",
    "featured": false,
    "optionLabel": "Supply",
    "options": [
      "1 month",
      "3 months",
      "6 months"
    ],
    "benefits": [
      "Covers morning and evening",
      "15% off as a repeat order",
      "Pause or cancel anytime"
    ],
    "ingredients": [
      "[[PLACEHOLDER: see individual product labels]]"
    ],
    "howItWorks": "[[PLACEHOLDER]] Follow the label directions for each product in the bundle.",
    "image": "images/products/the-daily-three.svg",
    "gallery": [
      "images/products/the-daily-three.svg",
      "images/products/_angle-bundles-2.svg",
      "images/products/_angle-bundles-3.svg",
      "images/products/_angle-bundles-4.svg"
    ],
    "imageAlt": "[[PLACEHOLDER: product photo of The Daily Three]]",
    "checkoutUrl": "https://example-shopify-store.myshopify.com/products/the-daily-three"
  }
];

/* ========================================================================== */

var TESTIMONIALS = [
  {
    "name": "Grace L.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] First supplement brand where I could actually work out how much of each thing I was taking."
  },
  {
    "name": "Sam O.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 5,
    "quote": "[[PLACEHOLDER]] I asked for the batch certificate and they sent it the same day. That told me a lot."
  },
  {
    "name": "Ines D.",
    "meta": "[[PLACEHOLDER]] Verified customer",
    "rating": 4,
    "quote": "[[PLACEHOLDER]] Subscription is genuinely easy to change, which is rarer than it should be."
  }
];

var FAQS = [
  {
    "q": "How do I place an order?",
    "a": "[[PLACEHOLDER]] Choose the product you want and select Buy now. You will be taken to our secure store to complete checkout."
  },
  {
    "q": "How long does delivery take?",
    "a": "[[PLACEHOLDER: confirm real timings]] Orders are usually prepared for dispatch within a couple of business days. Delivery estimates are shown at checkout."
  },
  {
    "q": "Is the packaging discreet?",
    "a": "[[PLACEHOLDER]] Yes. Orders arrive in plain outer packaging with no product branding on the outside."
  },
  {
    "q": "Can I return something?",
    "a": "[[PLACEHOLDER: confirm real policy]] Unopened items can be returned within the window shown at checkout. Some health and personal care items cannot be returned once opened."
  },
  {
    "q": "Do you offer a subscription?",
    "a": "[[PLACEHOLDER]] Where a repeat option is available it is shown on the product page at checkout, and you can change or cancel it at any time."
  },
  {
    "q": "Should I speak to a healthcare professional first?",
    "a": "[[PLACEHOLDER]] If you are pregnant or breastfeeding, take prescription medicine, or have an existing medical condition, speak to a qualified healthcare professional before starting anything new. See our medical disclaimer."
  },
  {
    "q": "How do I contact support?",
    "a": "[[PLACEHOLDER]] Use the contact form, or email us directly. We aim to reply within one business day."
  },
  {
    "q": "Where do you ship?",
    "a": "[[PLACEHOLDER: list real destinations]] Shipping destinations and rates are shown at checkout."
  }
];
